### ISSUE TITLE
The CLI should prompt users to verify their passphrase when they are importing/creating an account for the first time 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#1009]
Currently, the CLI only prompts the users once to enter in a passphrase once to store their account locally, and if they mistype the password by mistake they are locked out their account

Solution:
When they are importing/creating an account for the first time and they enter their inital passphrase, the CLI should have a verification prompt saying: `re-enter passphrase` and it it doesnt match then they have to start over.

**Comment by luyzdeleon** [comment]
Closed in favor of backlogged item #998
