### ISSUE TITLE
Every Pocket Node Type Should Have a Fast Sync Option 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#1012]
Issue:
When a user joins the network, it will take the node operator a node operator a long time to get synced up with the current blocks:

Proposal: 
enable a sync option that will allow users to download the last 500 blocks(because it's faster) and download the past blocks in the background. this will allow the node operator to begin interacting with the network sooner and begin servicing relays.

possible downfall:
They could be jailed/slashed if they don't have the data if contested/challenged, but I think this should be optional and we can communicate the risks.

**Comment by andrewnguyen22** [comment]
This is implemented in Tendermint
