### ISSUE TITLE
Pocket Core doesn't start with an empty keybase

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#1023]
**Describe the bug**
Currently, even if valid `node_key.json` and `priv_val_key.json` files are present in the datadir, if the keybase is empty, `pocket start` fails with the current error:

`2020/07/05 11:48:43 no keys stored in keybase, create a key pair by using "./main accounts create"`

**To Reproduce**
1. Run `pocket start` with an empty datadir

**Expected behavior**
`pocket start` successfully starts the Pocket Node.

**Comment by andrewnguyen22** [comment]
Keybase flag disabled, fixing now

**Comment by andrewnguyen22** [comment]
closed with #1014
