### ISSUE TITLE
Delete database with pocket reset

### ISSUE THREAD

**Issue by edjroz** [pokt-network/pocket-core#1035]
**Is your feature request related to a problem? Please describe.**
pocket reset should ask the user wether they wan't to delete their database in order to resynch.

**Describe the solution you'd like**
User writes `pocket reset`
receives a prompt asking wether they want to delete the database.
if yes, delete and resynch with the network

**Describe alternatives you've considered**
A complete reset only solution, however some users might not be looking forward to deleting their databases every time.

**Comment by andrewnguyen22** [comment]
@edjroz actually you're right, if they want to delete their databases and caches they can just remove them. A prompt is not a good solution for infra providers. Closing this issue now
