### ISSUE TITLE
/v1/query/tx endpoint returns malformed JSON

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#1046]
**Describe the bug**
Whenever querying this endpoint with a valid transaction hash, it returns the `TxResult`, with an appended `null` string.

**Fix**
Make sure the returned JSON is well formed.

**Comment by andrewnguyen22** [comment]
I cannot repeat this behavior, any more information would be helpful

**Comment by luyzdeleon** [comment]
Issue is not reproducible in RC-0.4.3 nor RC-0.5.0, closing.
