### ISSUE TITLE
Relay Metrics Endpoint

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1064]
**Is your feature request related to a problem? Please describe.**
Simple endpoint for collecting metrics on relays

**Comment by andrewnguyen22** [comment]
@luyzdeleon can I get some suggestions of what would be desirable?

**Comment by edjroz** [comment]
A relay counter would be ideal, as well as average relay time (likely just a single relay time anyone could aggregate them on their metrics dashboard)

**Comment by andrewnguyen22** [comment]
Noted thanks
