### ISSUE TITLE
Data race in peerList

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#108]
the addPeer function locks _after_ verifying the node is not present; two threads can enter the conditional, and one would patiently wait to add a duplicated node to the list.

https://github.com/pokt-network/pocket-core/blob/ef9bc018c8a44e320ac5cacd3c8f31162d93bb92/peers/peerList.go#L53

**Comment by andrewnguyen22** [comment]
But the contains function is also thread safe so I believe it’s okay

**Comment by andrewnguyen22** [comment]
Cause if we locked it first then the contains would never be able to execute

**Comment by iajrz** [comment]
Between a thread the letting go the Contains lock in line 54 and acquiring it again in line 55, another could acquire the lock at line 54.

**Comment by andrewnguyen22** [comment]
Good point, I’ll fix this

**Comment by iajrz** [comment]
I'm already on it ;)
