### ISSUE TITLE
Undocumented CLI query "pocket query daoOwner" returns "404 not found"

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1085]
cli/query.go contains a query called daoOwner
In testing, the command fails: 404 not found in RC-0.5.0 and RC-0.5.1
The command is not documented in the cli reference, so perhaps it is depreciated?
If so, a comment to that effect should be added in the code noting that.

**Comment by andrewnguyen22** [comment]
Fixed in RC-0.6.0
