### ISSUE TITLE
Default the re-encryption prompt from: app/cmd/cli/accounts.go:importArmoredCmd to be same as current

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1088]
Remove the re-encryption passphrase prompt and default it to the same as the current passphrase.

It is not just confusing, it is logically inappropriate to perform a passphrase change at the same time that you performing an import.

It the user wants to change a passphrase he has a command to do so.
Changing it here, without any typo double check is just asking for problems.

**Comment by andrewnguyen22** [comment]
I tend to agree. Care to tackle @BenVanGithub ?

**Comment by BenVanGithub** [comment]
Yes.  I'd like to take this one on.   Just review it carefully.. playing around with keys is pushing my envelope a bit.
