### ISSUE TITLE
[FEATURE REQUEST] Access signing_infos through smaller query

### ISSUE THREAD

**Issue by AusIV** [pokt-network/pocket-core#1091]
**Is your feature request related to a problem? Please describe.**

In order to monitor our nodes at Rivet, we like to have metrics on the number of missed block signings. At the moment, the only way to get this seems to be to query for /v1/query/state and parse the response - A response that is over 1MB and growing as the chain progresses.

**Describe the solution you'd like**

It would be very handy if we could get the "$.app_state.pos.signing_infos" for a particular address from /v1/query/state as its own request, rather than having to get the entire state of the chain and parse through it.

**Describe alternatives you've considered**

For now I'm parsing through the 1MB response, but that's going to become less and less viable as the chain grows.

**Comment by andrewnguyen22** [comment]
Hey @AusIV I think this is a great request. We will attempt to include `query/signing_info ` in the next release.

**Comment by AusIV** [comment]
Any chance there's a better way to do this now? It's gotten to the point where I've had to increase RPC timeouts to even be able to get a response from /v1/query/state.

**Comment by andrewnguyen22** [comment]
closed with c55213c34a90b8895da9cb9196587623e91ddf42

**Comment by andrewnguyen22** [comment]
> Any chance there's a better way to do this now? It's gotten to the point where I've had to increase RPC timeouts to even be able to get a response from /v1/query/state.

Will be included in RC-0.6.4 release
