### ISSUE TITLE
FAQ: Why is my node jailed?

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1092]
### PURPOSE
This issue is meant to serve as a list of common reasons for node jailing
### GUIDELINES
- If the node jailing doesn't fall within any of the following reasons please comment on this issue
- Although the issue is closed, FAQ issues are meant to be maintained and edited overtime
#### Validator is not signing blocks
- Validator, node, and p2p identity are not the same
  - Check the `[Tendermint RPC]/status/`endpoint and confirm that the `"id"` and the `"address":` field correspond with the expected validator address
  - Is your data-directory connected to the pocket-core instance `--datadir`?
  - Did you `pocket accounts set-validator`? Does `pocket accounts get-validator` return the expected address? Did you restart the instance?
  - Does your priv_val_key.json,  contain the same key as the node_key.json? Did you delete them (and priv_val_state.json) before running set-validator, and restart the instance?
- Is your process running properly?
  - Exit due to "too many open files"? Is your ulimit setup correctly?
  - Exit due to "invalid app hash"? Are you running the proper pocket-core version? Do you have enough resources for the minimum requirement?
  - Data/WAL-corruption? Are you shutting down the process and restarting often? Do you have enough resources for the minimum requirement?
- Is your node at the latest height? Is it falling behind due to P2P problems?
  - Check network setup to ensure you are syncing with good peers.
  - Try switching seeds/persistent peers with flags: `--seeds` and `--persistent peers`

### NOTES
If you don't know the answer to some of these questions, try the [docs](https://docs.pokt.network/) and reach out at Pocket Network's Discord or open an issue on github for support.

**Comment by jeremybeal11** [comment]
In addition, your node can not miss more than 6 blocks before it is jailed.

**Comment by BenVanGithub** [comment]
please add this file: priv_val_state.json
to the list of files that need to be deleted before set-validator in paragraph 1, item 4 above.

**Comment by andrewnguyen22** [comment]
> please add this file: priv_val_state.json
> to the list of files that need to be deleted before set-validator in paragraph 1, item 4 above.

Done

**Comment by PatrickM727** [comment]
> In addition, your node can not miss more than 6 blocks before it is jailed.

@jeremybeal11 do we have a list of reasons why node might be missing blocks as well?

**Comment by emedrano2112** [comment]
> > In addition, your node can not miss more than 6 blocks before it is jailed.
> 
> @jeremybeal11 do we have a list of reasons why node might be missing blocks as well?

Here are some @PatrickM727 https://github.com/pokt-network/pocket-core/issues/1215
