### ISSUE TITLE
Claim Resulted In an Invalid Merkle Proof: Code 66

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1094]
**Describe the bug**
I see too many code 66 claim failures to believe there is no bug in the merkle validation/generation system

See mainnet block `6666` as a case study. 

Investigate 
```
[{\"msg_index\":0,\"success\":false,\"log\":\"{\\\"codespace\\\":\\\"pocketcore\\\",\\\"code\\\":66,
\\\"message\\\":\\\"claim resulted in an invalid merkle Proof\\\"}\",\"events\":[{\"type\":\"message\",
\"attributes\":[{\"key\":\"action\",\"value\":\"proof\"}]}]},{\"msg_index\":0,\"success\":true,\"log\":\"
```

**Comment by BenVanGithub** [comment]
![Screenshot from 2020-10-09 14-57-13](https://user-images.githubusercontent.com/8411656/95635466-7dde7f00-0a5a-11eb-936d-4898c6b77885.png)
![Screenshot from 2020-10-09 16-18-05](https://user-images.githubusercontent.com/8411656/95635492-8b940480-0a5a-11eb-9274-9947ae927392.png)
![Screenshot from 2020-10-09 17-10-06](https://user-images.githubusercontent.com/8411656/95635520-9d75a780-0a5a-11eb-8bab-2d82f6b44c77.png)
Each screen shot is one hour apart .
shows... one claim leaving the list...
an hour later one claim has joined the list..
an hour later one claim has left the list..
but the vast majority of the list stays there, and has been there for days.
did an update to RC-0.5.1.... No change.

**Comment by andrewnguyen22** [comment]
Accidentally closed

**Comment by andrewnguyen22** [comment]
Executing here:

https://github.com/pokt-network/pocket-core/projects/36

**Comment by andrewnguyen22** [comment]
Closed with https://github.com/pokt-network/pocket-core/releases/tag/RC-0.5.2

**Comment by POKT-Discourse** [comment]
This issue has been mentioned on **Pocket Network Forum**. There might be relevant details there:

https://forum.pokt.network/t/pup-3-change-claimexpiration-to-24/311/1
