### ISSUE TITLE
Minimize Tendermint Info/Error Logs From Pex, P2P to allow more readability

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1096]
**Is your feature request related to a problem? Please describe.**
Modify tendermint to turn PEX/P2P to debug logs or at the very least, change the default config to not show those

**Comment by luyzdeleon** [comment]
I've given this a lot of thought, and I think having different logging streams could make a ton of sense. Instead of outputting everything, dividing the streams per module or category.

**Comment by andrewnguyen22** [comment]
@luyzdeleon tendermint already does [this](https://docs.tendermint.com/master/tendermint-core/running-in-production.html#logging) 

[more info](https://blog.cosmos.network/one-of-the-exciting-new-features-in-0-10-0-release-is-smart-log-level-flag-e2506b4ab756)
