### ISSUE TITLE
[FEATURE REQUEST] Staking with Cold Wallets

### ISSUE THREAD

**Issue by AusIV** [pokt-network/pocket-core#1101]
**Is your feature request related to a problem? Please describe.**

General best practice for protecting cryptocurrency assets is to keep the keys to the wallet holding the assets offline. When staking this is not possible, as the staker must have "hot" keys to sign messages, but the scope of those keys can be limited.

**Describe the solution you'd like**

There are a couple of possible options here.

ETH 2.0 offers a concept of an "exit address" on stakes. When you establish a stake, you can indicate a separate address to receive staking reward and receive the stake when it is unstaked. That way a hacker who compromises your key is limited to getting your stake slashed, but not stealing your tokens.

Another option would be if multisig addresses could, for example, require 2/2 for transferring tokens, but 1/2 for validation messages, a second key could be kept offline.

**Additional context**

In addition to allowing for a best practice of keeping keys offline, it would allow for a sort of delegated staking, where service providers can stake nodes on behalf of customers with limited exposure.

**Comment by andrewnguyen22** [comment]
Hey @AusIV I think this is a very compelling argument. I'm going to keep this open for discussion and internal reference with the PNI blockchain team. Thank you for this, I will provide updates. Full disclosure, very unlikely to make it into RC-0.6.0 but perhaps the major release after that.

**Comment by AusIV** [comment]
Oh, I didn't expect this that soon, I just wanted to get it on the roadmap for someday.

**Comment by andrewnguyen22** [comment]
Totally @AusIV thanks again

**Comment by miohtama** [comment]
For the comparison, I did a short dive on Cosmos staking, as both Pokt and Cosmos are based on Tendermind. I am very inexperienced with Cosmos/Tendermint, but looks like there is no separate addresses or keys making staking process safer by using a cold wallet. Instead, the recommended approach is to use hardware devices

https://github.com/iqlusioninc/tmkms

Looks like you can plug-in USB hardware wallet that contains your private key. However, Cosmos node must stil have this key connected all the time, and there cannot be "exit key" that is offline.

**Comment by andrewnguyen22** [comment]
Closing in favor of #1204
