### ISSUE TITLE
Remove Block Rollback from CLI

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#1103]
**Describe the bug**
When a user syncs their pocket node to the current state, it will crash and return am error every time i resume syncing my node(see example below):

```
error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 2ABDB006B6AE7286148AF213E34D2F598E91B4A4B9F361D73C7AF79644676689, got 1AD12ED32AEB480B14E93E19D23393EDB68190D1AE867234621923CEC5AC19A6
```

Even after the user updates their node to the **RC-0.5.1 nightly**, and conducts an unsafe rollback using the following command: `pocket util unsafe-rollback <random block number>

It will get caught up and return the same error(see above) at the same height it originally crashed on. 

**To Reproduce**
1. start a pocket node from 0 
2. if/when it crashes, start it again to resume operations 
3. wait for a few momemts
4. See an error

**Expected behavior**
the Node should resume syncing 

**Enviroment**
* Ubuntu LTS
* config.json DB = goleveldb

**Comment by andrewnguyen22** [comment]
Interestingly enough, it seems like there are `safe heights` to roll back to. I experienced this, but played around with a few heights and then was okay

**Comment by andrewnguyen22** [comment]
This feature is deprecated and needs to be removed from the CLI - I will rename the issue
