### ISSUE TITLE
HTTP Becomes Unresponsive While Validating Proofs

### ISSUE THREAD

**Issue by AusIV** [pokt-network/pocket-core#1115]
**Describe the bug**
When lots of messages to the effect of 

> Generate psuedorandom proof with 3859 proofs, at session height of 6921, for app: 8680faa1b8c324249cebd024e225f348eccd0fe9d877531cc8a22c16767f8893

Are being logged, the HTTP endpoints become completely unresponsive.

**To Reproduce**
1. Wait for a block validation to begin
2. Run queries (eg. pocket query height, or `curl http://locahost:8081/v1/query/height)`
3. At some point during the block processing phase, the above messages will begin printing, and the API will stop responding (requests will timeout).

**Expected behavior**

The service should prioritize serving requests over validating blocks.

***System***

Amazon Linux 2 ARM64

Observed on systems with a variety of cores and RAM.

**Comment by AusIV** [comment]
In my Go applications, I've found that putting a `runtime.Gosched()` in certain loops to help significantly with making sure different threads get a chance to run, while having minimal impact on the amount of time processes take if nothing else is demanding time.

Alternatively, a small time.Sleep() between validations may also help.

**Comment by andrewnguyen22** [comment]
Related: https://github.com/pokt-network/pocket-core/issues/1116

**Comment by andrewnguyen22** [comment]
@AusIV Thank you for the report and contribution

We are tackling this issue here:
https://github.com/pokt-network/pocket-core/projects/36

Will leave open until sufficiently solved

**Comment by andrewnguyen22** [comment]
Closed with https://github.com/pokt-network/pocket-core/releases/tag/RC-0.5.2
