### ISSUE TITLE
Psudo Random Proof loop?

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1116]
pages and pages and pages of
I[2020-10-10|16:34:16.324] Generate psuedorandom proof with 6526 proofs, at session height of 6761, for app: 306bc76aec5

eventually crashes the server.
stop and restart pocket fixes it.

**To Reproduce**
trying go get a reliable reproduce method.

just page after page like below... literally thousands of these.

![Screenshot from 2020-10-10 12-24-49](https://user-images.githubusercontent.com/8411656/95660464-1d9d1b00-0af6-11eb-89ad-b8506e366fd5.png)

**Comment by BenVanGithub** [comment]
![Screenshot from 2020-10-10 22-48-32](https://user-images.githubusercontent.com/8411656/95669214-fd984680-0b4b-11eb-8630-f470cfb445fe.png)
![Screenshot from 2020-10-10 22-46-45](https://user-images.githubusercontent.com/8411656/95669216-09840880-0b4c-11eb-8b1a-f3dcde3e13a6.png)
Same type of symptom here:  entire 1000 line history is: could not check tx
Pocket process is running but non responsive...
regular kill command won't stop it.
have to use force kill option -9 to get control

**Comment by andrewnguyen22** [comment]
@BenVanGithub The could not check tx is expected behavior

The other `loop` is just block processing:

We are tackling performance on the first one with https://github.com/pokt-network/pocket-core/projects/36

Keep any eye out for an update here

**Comment by andrewnguyen22** [comment]
Closed with https://github.com/pokt-network/pocket-core/releases/tag/RC-0.5.2
