### ISSUE TITLE
Node syncs but won't perform claims: Hash already found

### ISSUE THREAD

**Issue by amhed** [pokt-network/pocket-core#1117]
**Describe the bug**
Node constantly triggers "transaction hash is already found, this is a duplicate"

**To Reproduce**
- See Pocket node `8ce6e42739cf0e03c5f706901cb6248a7facc6db`, in comparison with other node with same hardware specs and located on same datacenter. 
- See 

- stdout sample
https://gist.githubusercontent.com/amhed/b3b0564f6a1f1a0a0af3f90c05d4e964/raw/ce67e2b4399cd3e9e37a93a0066ef280b95ad8ad/pokt-3-log.txt

**Expected behavior**
- Node is not jailed
- Node is synced/up to date with network
- Node is configured the same we configured others under our org
- Data folder and evidence db were wiped multiple times

We would expect similar behavior with other nodes on the same datacenter. 

**Screenshots**

![image](https://user-images.githubusercontent.com/579291/95686227-6665da00-0bb1-11eb-8da3-8cbc154340bf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser N/A
 - Version RC 0.5.0

**Comment by andrewnguyen22** [comment]
Possibly Related to Claim/Proof submission/validation


See:
https://github.com/pokt-network/pocket-core/projects/36

For active development on this front. Will leave open until we know this issue is solved

Thank you for the report

**Comment by amhed** [comment]
🚀

**Comment by andrewnguyen22** [comment]
Closed with https://github.com/pokt-network/pocket-core/releases/tag/RC-0.5.2
