### ISSUE TITLE
[FEATURE REQUEST] Pass in conf file path to pocket start

### ISSUE THREAD

**Issue by rBurgett** [pokt-network/pocket-core#1120]
`pocket start` does not appear to have a way of pointing to the config file on start. This forces the config data to be mixed in with the actual blockchain data. Usually, wallets/nodes provide a `-conf` flag which you can pass into the CLI with a path to your config file.

There needs to be either a flag passed into `pocket start` or an environmental variable that can be set to point to the conf file so that the configuration can be decoupled from the data itself. The conf file itself allows you to set specific paths to the key file and root directory and such which is perfect, but it's no good if I can't point the CLI to my conf file in the first place. If the CLI will only look in the default data directory for the conf file in order to read where the data directory is, then there is a problem.

Most wallets/nodes allow you to pass a `-conf` flag which points to the conf file. That would be my preference. But, others only allow you to do it via environmental variables. Ultimately, either works as long as it gets the job done.

Thanks

**Comment by andrewnguyen22** [comment]
Agreed @rBurgett will put on TODO for RC-0.6.0 thanks for the issue 👍

**Comment by rBurgett** [comment]
@andrewnguyen22 any word on the status of this? RC-0.6.0 came and went a while ago. I still really need a way to programmatically enter the config file location. As far as I know, the only way to load a config file is still to create the default directory structure so that the CLI will find the config file so that it can read and know where the data and key directories are. It was and still is a very awkward workflow. It'd be awesome if this could be addressed soon. Or, if it has already been addressed I'd appreciate an update. Thank you!

**Comment by rBurgett** [comment]
@andrewnguyen22 any new word on this? I desperately need to be able to pass in something like `--conf` to let the pocket node know where the config file is.

**Comment by kobrien** [comment]
any update on this? we would also like to specify separate dir for config
