### ISSUE TITLE
Convert Unit Testing To Integration Tests In Playground

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#113]
Any unit test that is simulating two different machines should be converted to integration tests, as there is race conditions in multithreaded tests 

Essentially, any unit test with time.Sleep() should be converted as this is not an acceptable solution

**Comment by iajrz** [comment]
I posit we should do mutation testing (to test the tests' relevance to our code), as well as our "regular" tests. This is crucial as we will need to build up _confidence of correctness_. This is a tool for mutation testing in go. https://github.com/zimmski/go-mutesting

**Comment by andrewnguyen22** [comment]
See #185 & #186
