### ISSUE TITLE
"public_key": null  on pocket query account, but exists on pocket query node for same address

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1159]
I've done every possible fix on this validator including total server wipe, reinstall, resync.
The node appears to to be working correctly:  passing all tests, passing relays, participating in consensus, etc.
Account balance does not update.
Only difference that I can identify between this node and all of the others that I manage:
1.) pocket query account 56870CF8331229C762A9E9C40FE7E22C34574D71 returns "public_key": null for this node, but returns a public key for all of the others.

Note:  This node was functioning fine until (approximately) when 0.5.1 was installed, but not positive on exact relationship.
screen shot of bad node..
![Screenshot from 2020-10-18 07-05-28](https://user-images.githubusercontent.com/8411656/96365686-65343000-1110-11eb-9db1-c4fbaa081338.png)

screen shot of good node...
![Screenshot from 2020-10-18 07-07-11](https://user-images.githubusercontent.com/8411656/96365722-9f053680-1110-11eb-96e2-2d46c316796b.png)

possibly related:  count "0"  from pocket query account-txs  on ALL ACCOUNTS

**Comment by andrewnguyen22** [comment]
@BenVanGithub Did you switch to the beta to see if this? Is this still an issue?

**Comment by BenVanGithub** [comment]
That node was non-pay for over a week.  Tried everything I could including rebuild from scratch on a new server.  Never got jailed, processed relays, never got paid.  Offered to leave it up if anyone wanted to investigate it.  Finally just unstaked it.  Without the ability to look at the tx-history I was out of research options.


Sent from Yahoo Mail for iPad


On Friday, October 23, 2020, 8:13 PM, Andrew Nguyen <notifications@github.com> wrote:




@BenVanGithub Did you switch to the beta to see if this? Is this still an issue?

**Comment by andrewnguyen22** [comment]
I see, I'm sorry to hear that. I have theories but will save them. I will close this issue, but reference it if ever a repeat.

**Comment by andrewnguyen22** [comment]
A similar case study with Ahmed from discord. The conclusion was that two of his nodes were servicing only 500 errors and was unable to produce a proper claim/proof because of this. Hard to say if this was the same case here, but wanted to report it. His public key was not shown either when you query the account, likely never paid so no pub key from the account was ever updated.
