### ISSUE TITLE
error in RPC Handler WriteErrorResponse: http: Handler timeout - - followed by crash

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1160]
Node crashed.
rebuilt and resyncd  node: F227B7C293E3AF6BEF18E9DBDCBC94F501C7CF14
intermittent error in RPC Handler WriteErrorResponse: http: Handler timeout
followed by crash.
Sample during start up.
![Screenshot from 2020-10-18 14-37-39](https://user-images.githubusercontent.com/8411656/96376972-14dcc280-1150-11eb-9b1c-3170951ae413.png)
Sample at point of crash.
![Screenshot from 2020-10-18 14-13-14](https://user-images.githubusercontent.com/8411656/96376987-2625cf00-1150-11eb-9d37-81d390a9c2b9.png)

RC-0.5.1

**Comment by BenVanGithub** [comment]
Just had the same error pattern on a different node:
Fixed both nodes using modified version of paragraph 1 item 4 from the "why is my node in jail?" FAQ... even avoided jail on the second node.

1.) delete the mentioned files
2.) restart pocket and get it to current block
3.) THEN set-validator to real validator

https://github.com/pokt-network/pocket-core/issues/1092

**Comment by andrewnguyen22** [comment]
Likely fixed in RC-0.5.2, but will keep open in the meantime

**Comment by andrewnguyen22** [comment]
Closed with RC-0.5.2
