### ISSUE TITLE
AccountTxs showing transactions from other accounts

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1188]
**Describe the bug**
Might be related to the concatenated events bug in pocketcore module https://github.com/pokt-network/pocket-core/issues/875

Account transactions endpoint is showing txs from other senders

Reproduce: `pocket query account-txs 90b4c5e1840b03486e013e0112394a861f311a74 1 1 false false`

See signature public key not correspond

I have tracked down many instances of this

**Comment by andrewnguyen22** [comment]
I assigned both projects here depending on scope

**Comment by edjroz** [comment]
Upon further investigation, tx search is not the culprit, tx are being miss indexed meaning a signer does not necessary match the event key, this leads to this bug.

Closed in favor of #1191
