### ISSUE TITLE
Shift Tx Indexer to pocket core

### ISSUE THREAD

**Issue by edjroz** [pokt-network/pocket-core#1191]
**Is your feature request related to a problem? Please describe.**
Currently by using tendermint's `txIndexer` can lead to miss indexing of a tx as evidenced in #1188. This happens because the event does not necessarily match the signer.

**Describe the solution you'd like**
A custom `txIndexer` that allows us to specify how we wanna index and store tx's

**Describe alternatives you've considered**
Modifying the tx Indexer on tendermint was considered however it would've led to breaking the ABCI standard in order to be able to pass down signer for comparassion of event & signer

**Comment by edjroz** [comment]
### Requirements

- Satisfy the standard tendermint interface:

```
type TxIndexer interface {

	// AddBatch analyzes, indexes and stores a batch of transactions.
	AddBatch(b *Batch) error

	// Index analyzes, indexes and stores a single transaction.
	Index(result *types.TxResult) error

	// Get returns the transaction specified by hash or nil if the transaction is not indexed
	// or stored.
	Get(hash []byte) (*types.TxResult, error)

	// Search allows you to query for transactions.
	Search(ctx context.Context, q *query.Query) ([]*types.TxResult, error)

	// Search allows you to query for transactions. However it only looks up for single conditions
	ReducedSearch(ctx context.Context, q *query.Query) ([]*types.TxResult, error)

	// DeleteFromHeight method added for rollback
	DeleteFromHeight(ctx context.Context, height int64) error
}
```

there's no benefit on breaking this standard since if our custom txIndexer satisfies this interface, we can still pass it down to tendermint which would in turn use our txIndexer rather than their own

https://github.com/pokt-network/pocket-core/blob/23eb9bc91c815cb4de201a6285ca0827df6b03df/app/tendermint.go#L71

### Caveats
- [ ] Disable txIndexer on tendermint's end 
- [ ] Design proper flow for indexing tx's on on pocket-core only (tx should likely during `DeliverTx` provided the passes, however this brings concerns about multiple txs arriving at the same time implying a single thread mechanism is required)
- [ ] New txIndexer must be injected into ante handler

**Comment by andrewnguyen22** [comment]
> ### Requirements
> * Satisfy the standard tendermint interface:
> 
> ```
> type TxIndexer interface {
> 
> 	// AddBatch analyzes, indexes and stores a batch of transactions.
> 	AddBatch(b *Batch) error
> 
> 	// Index analyzes, indexes and stores a single transaction.
> 	Index(result *types.TxResult) error
> 
> 	// Get returns the transaction specified by hash or nil if the transaction is not indexed
> 	// or stored.
> 	Get(hash []byte) (*types.TxResult, error)
> 
> 	// Search allows you to query for transactions.
> 	Search(ctx context.Context, q *query.Query) ([]*types.TxResult, error)
> 
> 	// Search allows you to query for transactions. However it only looks up for single conditions
> 	ReducedSearch(ctx context.Context, q *query.Query) ([]*types.TxResult, error)
> 
> 	// DeleteFromHeight method added for rollback
> 	DeleteFromHeight(ctx context.Context, height int64) error
> }
> ```
> 
> there's no benefit on breaking this standard since if our custom txIndexer satisfies this interface, we can still pass it down to tendermint which would in turn use our txIndexer rather than their own
> 
> https://github.com/pokt-network/pocket-core/blob/23eb9bc91c815cb4de201a6285ca0827df6b03df/app/tendermint.go#L71
> 
> ### Caveats
> * [ ]  Disable txIndexer on tendermint's end
> * [ ]  Design proper flow for indexing tx's on on pocket-core only (tx should likely during `DeliverTx` provided the passes, however this brings concerns about multiple txs arriving at the same time implying a single thread mechanism is required)
> * [ ]  New txIndexer must be injected into ante handler

Why is it a requirement to satisfy the Tendermint interface?

We don't want to use Tendermint at all to index transactions because they `by default` index transactions async. Since we use the indexer for replay protection, we need a synchronous function. I don't see any benefit in keeping transaction indexing in Tendermint, thus there is no benefit in satisfying the interface AFAIK

**Comment by edjroz** [comment]
it requires less tinkering by satisfying the interface there's no need to modify the `anteHandler` which expects the interface.

The interface itself makes no assumptions on the nature of synchrony it only works as a gateway into our implementation. 

However point is taken!

An "easy" implementation that does not require to use the interface would be to create a txIndexer service which would through channels could receive 1 tx at a time.


```go
// DeliverTx implements the ABCI interface.
func (app *BaseApp) DeliverTx(req abci.RequestDeliverTx) (res abci.ResponseDeliverTx) {
	var result sdk.Result
        ...
	if result.IsOK() {
            app.TxIndexer <- result
        }
	return ...
}
```

This makes Sure that the txIndexer receives all the tx's in order and gives us the ability to index them as they come.

**Comment by andrewnguyen22** [comment]
Interesting idea! I get what you're saying, but remember the AnteHandler param is something we modified, so we can modify it again too
