### ISSUE TITLE
Remove Session DB

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1194]
According the docs " pocket reset "
    Reset the Pocket node.
    Deletes the following files / folders:
        .pocket/data
        priv_val_key
        priv_val_state
        node_keys
- - - 
Is there any reason that session.db needs to survive a reset?
It seems to cause trouble.
Does it add value in any way by persisting?

**Comment by andrewnguyen22** [comment]
@BenVanGithub I'm grasping at straws here, but the efficiency of maintaining previous sessions can be helpful in certain situations. In this case, I don't think that it makes sense to keep sessions around during a reset.

Perhaps sessions shouldn't persist in a database at all...

**Comment by andrewnguyen22** [comment]
I would like to update this issue to delete the entire sessionDB, as it seems like it might only be helping edge case scenarios to maintain a database of sessions
