### ISSUE TITLE
Print default config.json with CLI

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1201]
**Is your feature request related to a problem? Please describe.**
Print the default config.json for easy replace via CLI

**Comment by BenVanGithub** [comment]
Sorry, I don't "get" the concept.
It sounds like you're saying "make a cli command that executes "cat ~/.pocket/config/config.json"
What am I not seeing?

**Comment by andrewnguyen22** [comment]
The default config.json is different than config.json

This is to help node runners identify the new releases default config without altering their own

**Comment by BenVanGithub** [comment]
OK.. Cool.. I definitely see the utility in that.  In fact I feel kinda silly not realizing what you meant.
