### ISSUE TITLE
"assertion failed" during node syncing on M1 Mac

### ISSUE THREAD

**Issue by JackALaing** [pokt-network/pocket-core#1203]
When trying to sync a full node on an M1 Mac, the sync randomly hangs with the following error message:

`assertion failed [*ret_index + 2 == num_insts]: RET should be second last instruction in translation
(StateRecovery.cpp:304 check_cfg)`

The terminal also hangs, including being unable to do ^C. 

If you open a new terminal tab, you can run pocket start again and it will pick up where it left off, but then randomly hang again.

This is most likely an error with dependencies and Apple's Rosetta 2. For example, I'm also unable to update pocket core using Homebrew.

The only similar errors I found on Google were (also M1 Macs):

- https://github.com/pulumi/pulumi/issues/5859
- https://github.com/prysmaticlabs/prysm/issues/7950

**Comment by edjroz** [comment]
This is likely to be expected as of the moment writing this tooling such as golang, leveldb C/C++ compilers are working to get compatibility.

I am curious as to how you ran it? 

Build from source using rosetta + running with rosetta?

**Comment by JackALaing** [comment]
I had installed it on my Intel MacBook Air then transferred all files to my M1 MacBook Pro using Apple’s Migration Assistant. This transferred pocket over with it.

**Comment by andrewnguyen22** [comment]
I don't believe we are pursuing a solution at this time. Feel free to reopen
