### ISSUE TITLE
[FEATURE REQUEST] Support for Operator Address

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1204]
Modify pocket stake/unstake process to allow for optional unstaking/payment address (different from stake address)

Abstract: Pocket Network’s security model for Validator nodes could be greatly enhanced by a protocol and associated code modification which allowed an unstaking/payment address to be defined at the same time that the stake command is executed.  This backward compatible enhancement would allow all node runners to protect themselves in the event a bad actor gaining control of their server and accessing the private key which controls the staking address to unstake and eventually steal the stake.  This would also allow node owners to trustlessly delegate the operation of their nodes to third parties who would not be able to steal the funds.

Implementation:

As protocol modifications go... this is not excessive and should be fully backward compatible (although not retroactive).  Three modifications are required:

1.) Modify the actions associated with the stake command to accept an additional address - the unstake/payment address.
2.) Modify the coin minting action to pay the minted amount to the unstake/payment address (if one exists, otherwise pay as usual)
3.) Modify the actions associated with the unstake command to move the funds to the unstake/payment address (if one exists, otherwise pay as usual).  And to require NOT the validator's signature, but the unstake address' signature.

I’m not trying to minimize the amount of work, testing and auditing that a change like this would require, but I am saying that this (or something similar) would represent a huge increase in the day to day security of all nodes and I ask that it be given full consideration for inclusion in the road map of the 6.0 release.

Comments and questions and criticisms are welcomed.

**Comment by andrewnguyen22** [comment]
I agree with the general spirit of this proposal. The details I will need to work over in my mind and give further thought to. 

It should be noted that Pocket Inc. ecosystem participants have also requested a similar issue to allow them to not own their client's private key and to be able to operate nodes on a users behalf. 

One immediate pushback that comes to mind is the timeline for incorporating in RC-0.6.0 seems more likely RC-0.7.0

Seems like a more formulated version of https://github.com/pokt-network/pocket-core/issues/1101

Will close https://github.com/pokt-network/pocket-core/issues/1101 in favor of this issue but bring over the original conversation

**Comment by andrewnguyen22** [comment]
From #1101 

AusIV:

> Is your feature request related to a problem? Please describe.
> 
> General best practice for protecting cryptocurrency assets is to keep the keys to the wallet holding the assets offline. When staking this is not possible, as the staker must have "hot" keys to sign messages, but the scope of those keys can be limited.
> 
> Describe the solution you'd like
> 
> There are a couple of possible options here.
> 
> ETH 2.0 offers a concept of an "exit address" on stakes. When you establish a stake, you can indicate a separate address to receive staking reward and receive the stake when it is unstaked. That way a hacker who compromises your key is limited to getting your stake slashed, but not stealing your tokens.
> 
> Another option would be if multisig addresses could, for example, require 2/2 for transferring tokens, but 1/2 for validation messages, a second key could be kept offline.
> 
> Additional context
> 
> In addition to allowing for a best practice of keeping keys offline, it would allow for a sort of delegated staking, where service providers can stake nodes on behalf of customers with limited exposure.

Andrewnguyen22:

> Hey @AusIV I think this is a very compelling argument. I'm going to keep this open for discussion and internal reference with the PNI blockchain team. Thank you for this, I will provide updates. Full disclosure, very unlikely to make it into RC-0.6.0 but perhaps the major release after that.

miohtama:

> For the comparison, I did a short dive on Cosmos staking, as both Pokt and Cosmos are based on Tendermind. I am very inexperienced with Cosmos/Tendermint, but looks like there is no separate addresses or keys making staking process safer by using a cold wallet. Instead, the recommended approach is to use hardware devices
> 
> https://github.com/iqlusioninc/tmkms
> 
> Looks like you can plug-in USB hardware wallet that contains your private key. However, Cosmos node must stil have this key connected all the time, and there cannot be "exit key" that is offline.

**Comment by andrewnguyen22** [comment]
Just to note:

Another component here, is that the OP's approach may not satisfy the non-custodian legal requirements of ecosystem participants not wanting to ever have custody over any POKT value. (You must give the third party the PK with the amount of the staked POKT). I know this issue wasn't originally intended for the staking as a service delegation, but if we are going this route we might want to consider capturing all the value from a feature like this

EDIT: Invalidated. See following comments

**Comment by BenVanGithub** [comment]
As written, it does not require that the operator have custody at any point.  However, in practice, it would expect most users to allow the operator temporary control of the staking funds during set-up simply because it's faster and easier.
Temporary Custodial Flow:
T.1.)  Customer creates payment/withdrawal address (keeps PK, gives PubAdd to operator)
T.2.)  Operator creates Staking address (keeps PK, gives PubAdd to customer)
T.3.)  Customer Funds PubAdd with stake + buffer
T.4.)  Operator submits stake transaction.
T.4.a) Operator sends customer stake address PK
T.5.)  Customer confirms via blockchain lookup that the funds are staked and can only xfer to his pay/withdraw address.

Non-Custodial Flow:
NC.1.)  Customer creates payment/withdrawal address (keeps PK, gives PubAdd to operator)
NC.2.)  Customer creates Staking address (keeps both keys at this step)
NC.3.)  Customer funds Staking address
NC.4.)  Customer submits staking transaction - goes directly to jail
NC.5.)  Customer gives staking PK (which does not represent ownership anymore because you can't use it to get control of the funds) to Operator.
NC.6.)  Operator stands up node.  
NC.7.)  Customer confirms via blockchain lookup that pay/withdraw address is correct.

Notes:  
1.) Stake directly to jail - resolved
2.) Fees - resolved


Regarding multi-sig:
Multi-signature simply shares and spreads responsibility.  It has its uses, but I don't see how it adds anything but complexity to this issue.

**Comment by andrewnguyen22** [comment]
@BenVanGithub You are correct about the non-custodial flow. I believe you satisfied the original request.

Clarifications
1) NC.3 Yes, if an address is funded, it can become a validator

2.c) unstake command and all other transfer commands come from pay/withdraw address
It seems less clean (and less feasible to separate transaction actions like this). I think the withdrawal address is enough security for this feature.

**Comment by BenVanGithub** [comment]
In the temp custody flow: Unstake command has to be signed by the withdrawal address or the operator could (accidentally or intentionally) hold the funds hostage by refusing to unstake... but.. that could be fixed by modifying the flow rather than the code.
What do you mean "deposit address"?  stake address or pay/withdraw address?

**Comment by andrewnguyen22** [comment]
@BenVanGithub `holding the funds hostage` can be flipped by in the scenario where funds are `unstaked` without paying the service provider. In both cases, I'd say this isn't a protocol level issue

**Comment by BenVanGithub** [comment]
` I'd say this isn't a protocol level issue`
I agree.  Modified flow to address it.

**Comment by BenVanGithub** [comment]
@andrewnguyen22 hope it's OK to edit and delete my comments on here... I'm deleting questions as they get resolved so that this doesn't end up being like a thread on DIscord where the information gets lost in all the chatter.

**Comment by mokn** [comment]
I'd like to describe a different implementation of the same problem that OP is aiming to solve:

Instead of having a designated minting address there is a different type of account. This account, like the current implementation, would enable a private key (PK) to validate and sign blocks, but would also allow a multisig for basic transactions such as send and unstake. The end result is that each Pocket Core function would be separate and modular from the signing scheme associated with it.

In practice, anyone running the node would have access to the validating PK. The owner(s) of the POKT would have access to the multisig PK's, which would provide better protection from malicious transfers.

Some contemplated questions about my proposed solution:

1) Security impacts?

2) Complexity of implementation? 

3) Does enabling a minting address versus allowing multiple PK's to do different functions in one account provide a stronger foundation for future features or scaling efforts?

**Comment by BenVanGithub** [comment]
@mokn I'm pretty sure that multi-sig is not a solution that applies here.  I think if you tried to spec it out for implementation, you will find that you end up having to do exactly what the original proposal suggests and then add multi-sig to the minting/payment address.
Unless I greatly underestimate the Tinderment code, it is not going to support multi-sig block signing and (if it did) all of the keys would need to be on the server.
Perhaps you are envisioning something more like a hierarchical address scheme?  Where the customer controlls the top address and gives the operator a subordinate key pair to stake to?  Unfortunately, even in that scenario, you would need to build the underlying double address structure that is being proposed.

**Comment by andrewnguyen22** [comment]
Yes, two addresses or some workaround signing implementation would be required and Tendermint does not support multi-block signing

**Comment by mokn** [comment]
> Perhaps you are envisioning something more like a hierarchical address scheme? Where the customer controlls the top address and gives the operator a subordinate key pair to stake to?

This is exactly what I was thinking, not any kind of multisig signing

**Comment by BenVanGithub** [comment]
Note:  Two step process for adding output address to existing Validators:
1.)  Use edit stake command to provisionally identify the output address.
2.)  Output address owner must submit a TX (perhaps as simple as a duplicate of the edit stake command) signed by the Provisional address to prove/confirm ownership and control of that address.
3.)  Prior to address confirmation, original address can still edit stake and change the provisional address.

The purpose of the two step process is to insure that you cannot "typo" or commit some other mistake that puts the stake into an address which no one has control of.
