### ISSUE TITLE
Create FAQ issue to answer how does the prometheus relay metrics work

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#1213]
**Is your feature request related to a problem? Please describe.**
Currently there's no documentation on how to successfully extract the Relay Metrics collected by the Pocket Core node.

**Describe the solution you'd like**
A FAQ issue in this repo explaining how do the Relay Metrics feature works.

**Comment by andrewnguyen22** [comment]
@luyzdeleon are there open reports from internal infra about Relay Metrics not working?

**Comment by edjroz** [comment]
@luyzdeleon could we compile a list of said FAQ's to properly structure the document, otherwise it just seems like even if we write it we won't satisfy the requirement.

**Comment by andrewnguyen22** [comment]
? Just search the tag: FAQ

**Comment by edjroz** [comment]
Isn't the Idea to compile FAQs for Relay Metrics, not overall FAQs
