### ISSUE TITLE
Port 26656 unreachable

### ISSUE THREAD

**Issue by sfoxdev** [pokt-network/pocket-core#1216]
After upgrade to RC-0.5.2.9 each node once a day become unreachable on port 26656.
No errors in logs, node is node jailed and ports 26657 and 8082 works okay, so I can check node status using 
```
curl localhost:26657/status
```
and
```
pocket query node ...
```
No additional configuration changes with service or server were made between using version 0.5.1 and 0.5.2.9.
The same issue appeared on 10 nodes in 3 days in row.
After restarting node or rebooting server a node works for one day and dies.

**Comment by andrewnguyen22** [comment]
Hey @sfoxdev sorry for the delayed response. Yesterday was quite busy. 

>each node once a day become unreachable on port 26656

I see, how are you testing this?
>node is node jailed and ports 26657 and 8082 works okay
I assume you mean node is `not` jailed. In this case, what symptoms are you experiencing that might cause you to open an issue here?
>node works for one day and dies
Dies? What is the exit code? What is the termination log?

Do you mean falls back out of sync?

Can you tell me what the value for curl localhost:26657/net_info is?

**Comment by sfoxdev** [comment]
Problem caused by application, because it reject all incoming requests if limit set to 10. Configuration was changed after using command `pocket util update-configs` to
```
"MaxNumInboundPeers": 10,
"MaxNumOutboundPeers": 10,
```
Solved by setting up 
```
"MaxNumInboundPeers": 250,
"MaxNumOutboundPeers": 250,
```

I faced with this problem when use Prometheus monitoring tool to check service health.

Prometheus with blackbox is one of many tools and online healthcheck services that check service availability by TCP port. So it's normal to check service status by port and it's weird why application simply reject incoming connection without any check, because was used limit from configuration, it should check who tries to connect.

**Comment by andrewnguyen22** [comment]
I'm glad to hear you solved your issue. What I hear, is that you maxed out your peers and your nodes were so peer-healthy your custom P2P monitoring through Prometheus was blocked. The only caveat with your 'solution' to this 'problem' with is that increasing your peers to 250 and 250 you run the risk of high resource consumption.

There are many other ways to monitor the P2P health (like 26657:net_info or 26657:status).

**Comment by sfoxdev** [comment]
What do you mean saying `There are many other ways to monitor the P2P health (like 26657:net_info or 26657:status).` ?
For example I use 3 different tools to monitor if my service is healthy:
- Prometheus
- AWS DNS healthcheck or Cloudwatch
- online services like Uptime, StatusCake, Uptimerobot, etc.

Show me the real example of automated monitoring for service in such case, using `26657:net_info` or `26657:status`

**Comment by andrewnguyen22** [comment]
>Show me the real example of automated monitoring for service in such case, using 26657:net_info or 26657:status

Your custom solution where you are sending some arbitrary request to the peer port is likely not optimal.

Here are three examples:

net_info endpoint
```
curl --location --request GET 'http://localhost:26657/net_info'

{
    "jsonrpc": "2.0",
    "id": -1,
    "result": {
        "listening": true, // I'm listening which is healthy
        "listeners": [
            "Listener(@)"
        ],
        "n_peers": "0", // n_peers is 0 which is unhealthy
        "peers": []
    }
}
```

Status endpoint
```
curl --location --request GET 'http://localhost:26657/status'

{
    "jsonrpc": "2.0",
    "id": -1,
    "result": {
        "sync_info": {
            "latest_block_height": "271", //  height is not the latest
            ...
            "catching_up": false              // I'm not syncing right now
        },
        "validator_info": {
            "address": "3E3E9E274A9A1838BAFCB0A6E42111DEA1704057", // my validator information is not as expected
        }
    }
}
```

_Where can I find this information?_

[Monitoring Tendermint Docs](https://docs.tendermint.com/master/tendermint-core/running-in-production.html#monitoring-tendermint)

_Want to use prometheus instead to monitor health?_

Check out this gauge:

```
p2p_peers | Gauge |   | Number of peers node's connected to
```

`If p2p_peers == 0 -> Trigger Grafana alarm`

[Here's all prometheus exposed metrics](https://docs.tendermint.com/master/nodes/metrics.html#metrics)

**Comment by sfoxdev** [comment]
Looks you haven't idea what is TCP healthchecks for and how they works for services that I asked above. 
Your examples doesn't make any sense.

**Comment by andrewnguyen22** [comment]
I feel like a broken record:

TCP health checks are not optimal for this application

Just because a Port is reachable doesn't mean you are 'healthy'. 

You even specifically asked for prometheus metrics so I gave you the P2P prometheus gauage and a list of 30+ and the Official Tendermint documentation for monitoring with Prometheus

**Comment by sfoxdev** [comment]
Yes, you are right, you are like a broken record :)

Each normal monitoring system is based on two types of checks, internal and external:
- For internal, I already using different Prometheus metrics (including Tendermint) and they works okay.
- For external, you can only check by TCP port or domain name. Why do you need that? Pocket service require 80, 443(e.g. Nginx) and 26656 TCP ports to be opened externally. So such TCP check is required too. Let's imagine that you or someone of your team updated firewall rules and after that ports become unreachable, so in that case your internal check tells you that service is healthy, but it wouldn't be accessible for worldwide. It's only one example of possible issues.

Unfortunately, I haven't too much time for this. I solved (temporary) that issue on my side, but devs should fix it.
