### ISSUE TITLE
Add password check for new account creation and PK imports

### ISSUE THREAD

**Issue by mokn** [pokt-network/pocket-core#1223]
There is currently no password check for creating a new account or importing an existing private key. This creates difficulty in ensuring that a complicated password is written well the first time. 

The current steps are:

`pocket accounts create` 
`Enter Passphrase:`
`Account generated successfully:`

I would ask to add in `Enter passphrase again` to ensure it is done correctly.

**Comment by edjroz** [comment]
I think this requires attention since a missed key might invalidate an account, it's also common UX to verify passphrasses.
