### ISSUE TITLE
Node stops adding new blocks on a clear hour boundary seemingly randomly

### ISSUE THREAD

**Issue by Garandor** [pokt-network/pocket-core#1229]
**Describe the bug**
My node chugs along until on a clear hour boundary (last time it happened at 3 or 4am) it just stops adding to the chain.
Node must be restarted to continue

**Expected behavior**
Block production to continue

**Screenshots**
![image](https://user-images.githubusercontent.com/4237655/106183995-f5056380-616e-11eb-9b98-3bbd9c162d21.png)
Systemd log around the problematic timeframe : [nodefreeze.log](https://github.com/pokt-network/pocket-core/files/5889485/nodefreeze.log)

**Desktop (please complete the following information):**
 - OS: Archlinux x86_64
 - Pocket  RC-0.5.2.9

**Comment by andrewnguyen22** [comment]
@Garandor sorry to hear about your issue.

Have you tried the FAQ debug items?
https://github.com/pokt-network/pocket-core/issues/1215

If so, please provide me with the :26657/net_info and :26657/consensus_state output

**Comment by Garandor** [comment]
Turns out there was a
 E[2021-01-28|10:09:09.509] CONSENSUS FAILURE!!!                         module=consensus err="could not find validator set for height #17076

in my node. i have attached the log around the consensus failure

**Comment by andrewnguyen22** [comment]
What version are you running?

**Comment by Garandor** [comment]
Pocket RC-0.5.2.9

**Comment by andrewnguyen22** [comment]
@Garandor Sorry deleted my comment, saw it in the original

**Comment by andrewnguyen22** [comment]
@Garandor Can you tell me your specs for the machine you're running on ?

Memory, CPU, etc?

**Comment by andrewnguyen22** [comment]
So I've seen this issue before. But only when using an old C-levelDB backup from previous beta's and RC-0.5.1 and RC-0.5.2.9 is a GolevelDB only application. Could you tell me where you're getting your backup data directory?

Also are you shutting down your node before performing the backups?

**Comment by Garandor** [comment]
4-core AMD laptop processor, 8GB RAM

$ cat /proc/cpuinfo
processor       : 0-3
vendor_id       : AuthenticAMD
cpu family      : 18
model           : 1
model name      : AMD A6-3400M APU with Radeon(tm) HD Graphics
stepping        : 0
microcode       : 0x3000027
cpu MHz         : 854.184
cache size      : 1024 KB


The database for this node was copied from a stopped VPS node that was bootstrapped from 0 on the 5.2.9RC

I have not yet performed any backups on this node

**Comment by Garandor** [comment]
![image](https://user-images.githubusercontent.com/4237655/106192244-e96b6a00-6179-11eb-8ed3-cac6afc8073d.png)

After restarting the frozen node, I'm stuck in a loop. Guess I'll throw in the db backup again 

Looks weird that stateHeight is lower than storeHeight

**Comment by andrewnguyen22** [comment]
That usually means the DB is corrupted somehow. I've seen it when resources are too low or Ulimit is set too low, or shutdown process corrupted it.. (your resources look fine)

I'm assuming you move over the entire `<data-dir>/data/*` folder when initializing this node?

The consensus failure isn't something I have seen before in non corrupted backups, a great way to check this is by using the pocket provided backup that is known to work: You can find it here: https://github.com/pokt-network/pocket-core/releases/tag/RC-0.5.2.9 but unfortunately it's on block 13K

**Comment by Garandor** [comment]
Might have been causd by an unclean node shutodwn where the process was SIGKILLed #1230
Interesting that this didnt lead to an immediate consensus failure, but only surfaced after about a day of running the node.
I started resync from my backup I used originally and the node successfully passed the block  that had the consensus failure earlier

**Comment by andrewnguyen22** [comment]
I see... It's hard to tell the actual cause, but I do kind of worry about repeat behavior when using the same backup. In anycase, I will close this for now. Feel free to re-open if this continues to surface

**Comment by Garandor** [comment]
If it happens again I'll retry with the official backup before reopening

Just wondering - correct me if i'm wrong - if the backup was corrupted and caused the consensus failure - shouldn't resync have failed with a consensus failure at the same block?
