### ISSUE TITLE
cmd + C or CTRL + C, not stopping pocket.

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-core#1230]
**Describe the bug**
When running pocket, and the user wants to stop it by doing `cmd + c` or `ctrl + c`, the same appears to be stopping a couple of procedures within the logs, but doesn't kill the process. Therefore, leads the user to a data/WAL corruption. It is known that this is definitely not the best way to stop pocket (refer to the FAQ here), but we would like to fix this as it was working before, and it's working for some users.

**To Reproduce**
1. Run pocket: `pocket start`
2. Let it sync up with a couple of blocks.
3. Go to the terminal and do: `cmd+c` or `ctrl+c`.
4. Notice that you'll have a couple of stopping entries in the logs, but the process would not be killed:
https://www.loom.com/share/bc3289a05a24475f8e7cc1bcf40bcd3a

**Expected behavior**
Pocket must be stopped.

**Screenshots**
https://www.loom.com/share/bc3289a05a24475f8e7cc1bcf40bcd3a

**Comment by koen84** [comment]
Same thing if pocket start is called from a unitfile, it's not responding to `systemctl stop` or `systemclt restart`.

**Comment by andrewnguyen22** [comment]
@koen84 if you could follow up on the environment variable thing (madvdontneed=1) and see if the issue persists, that would be helpful

(if not set, can sometimes cause this issue with the child process)

**Comment by Garandor** [comment]
I just added
`Environment="GODEBUG=madvdontneed=1"`
to my unitfile and will report if I run into the issue again

**Comment by andrewnguyen22** [comment]
@Garandor Thank you for this

**Comment by Garandor** [comment]
Happened again. This is a conflation of #1229 where my node stopped block production because of a corrupted DB after about a day of operation and the refusing-to-cleanly-shutdown problem from here

Following situation:
![image](https://user-images.githubusercontent.com/4237655/106408464-85140900-640c-11eb-9984-7435009bdc3a.png)

`systemctl stop pocket` with SIGTERM did not stop the node until it ran into timeout ad got SIGKILLed around 20:24 (last blockupdate in log is at 19:04), see [corruption.log](https://github.com/pokt-network/pocket-core/files/5901587/corruption.log)
block production stopped with the following log entry
`Jan 31 19:20:28 poktnode pocket[333]: E[2021-01-31|19:20:28.225] CONSENSUS FAILURE!!!                         module=consensus err="failed to write batch: leveldb/table: corruption on data-block (pos=2065234): checksum mismatch, want=0xf9d35129 got=0xfeca4b0c [file=459128.ldb]" s`

My unitfile
```
[Unit]
  Description=pocket
  After=network-online.target

[Service]
  Type=simple
  User=pokt
  Group=pokt
  WorkingDirectory=/home/pokt/.pocket
  ExecStart=/home/pokt/bin/pocket start --mainnet
  Environment="GODEBUG=madvdontneed=1"

  KillMode=control-group
  KillSignal=SIGTERM
  TimeoutStopSec=200

  Restart=always
  RestartSec=5
#  StandardOutput=append:/var/log/pocket/output.log
#  StandardError=append:/var/log/pocket/error.log

[Install]
  WantedBy=multi-user.target
```

**Comment by andrewnguyen22** [comment]
This is a first for me...
> block production stopped with the following log entry
Jan 31 19:20:28 poktnode pocket[333]: E[2021-01-31|19:20:28.225] CONSENSUS FAILURE!!! module=consensus err="failed to write batch: leveldb/table: corruption on data-block (pos=2065234): checksum mismatch, want=0xf9d35129 got=0xfeca4b0c [file=459128.ldb]"

Can you please describe your datadir backup process? I agree with you though, this seems that it could be related to the 'unclean shutdown' issue 

Also, you mentioned trying the 'official' backup at some point for experimentation. That would be very helpful

**Comment by Garandor** [comment]
Though this problem is offtopic to the current issue, I think my solution to the "checksum mismatch" Problem could be interesting for future reference
It looks like the data corruption was due to a faulty RAM module. fsck returned nothing unusual so I ran memtest86+ and it returned heaps of errors. Threw out the old RAM module, reran memtest with no failures and now my node exhibits https://github.com/pokt-network/pocket-core-deployments/issues/183 behavior (i.e. stops roughly every day) but `systemctl restart` does not lead to a corrupted DB anymore (at least so far, even though the restart still happens with SIGKILL after SIGTERM timing out without pocket exiting)

**Comment by andrewnguyen22** [comment]
@Garandor thank you for the update... That's very interesting. Just an update on this specific issue, we are implementing a Pocket Stop command for the CLI that will hopefully end these problems

**Comment by andrewnguyen22** [comment]
PR https://github.com/pokt-network/pocket-core/pull/1233

**Comment by thomasdephuoc** [comment]
Hi @andrewnguyen22 , thanks for the update on this. I'm curious about why you chose to implement a new native "pocket stop" function instead of supporting the sigterm signal, and what would be the timeline would be for container signals (such as sigterm) handling.

Happy to provide more information.

**Comment by oten91** [comment]
Hi @thomasdephuoc, pocket already support the following stop signals : SIGTERM, SIGINT, SIGQUIT. Please let us know if you are having any trouble with the signals running on a container.

On the other hand we have multiple reports about users experiencing issues while stopping pocket on various scenarios, we are adding the stop command as an additional way to stop pocket gracefully.

**Comment by thomasdephuoc** [comment]
Hi @oten91, thanks for the quick feedback.

At Skillz we have problems with the signals running on a container indeed. Pocket doesn't react when SIGTERM is launched in a Docker container, and gets killed at the end of the timeout (which we set to 45 seconds), leading to chain data corruption issue when the programme gets SIGKILL. 

The node cannot get launched again as it requires a full catchup with the chain data and a complete _pocket reset_, leading to quite a downtime fairly often.

We get the following error:

`2021/02/01 21:34:40 no chains.json found @ /pocket/config/chains.json, defaulting to empty chains
I[2021-02-01|21:34:40.629] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2021-02-01|21:34:40.629] Starting localClient                         module=abci-client connection=query impl=localClient
I[2021-02-01|21:34:40.629] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[2021-02-01|21:34:40.629] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[2021-02-01|21:34:40.629] Starting EventBus                            module=events impl=EventBus
I[2021-02-01|21:34:40.629] Starting PubSub                              module=pubsub impl=PubSub
I[2021-02-01|21:34:40.629] Starting IndexerService                      module=txindex impl=IndexerService
I[2021-02-01|21:34:40.629] ABCI Handshake App Info                      module=consensus height=17413 hash=E7602B81C290C71037724432D42C7183304F79E1F0F7233561AF481C9E978F92 software-version= protocol-version=0
I[2021-02-01|21:34:40.629] ABCI Replay Blocks                           module=consensus appHeight=17413 storeHeight=17414 stateHeight=17413
I[2021-02-01|21:34:40.629] Replay last block using real app             module=consensus 
panic: Could not find validator set for height #17413
goroutine 1 [running]:
github.com/tendermint/tendermint/state.getBeginBlockValidatorInfo(0xc00000c5a0, 0x13ed0c0, 0xc0028eed20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/state/execution.go:337 +0x867
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x13dad60, 0xc002fd9500, 0x13e4440, 0xc000a0f760, 0xc00000c5a0, 0x13ed0c0, 0xc0028eed20, 0x7, 0xc002be43a0, 0x7)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/state/execution.go:294 +0x1f6
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000a62200, 0xa, 0x0, 0xc002be4390, 0x7, 0xc002be43a0, 0x7, 0x4405, 0x115c9d, 0xc002be0980, ...)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/state/execution.go:135 +0x17a
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0031a6fb0, 0xa, 0x0, 0xc002be4390, 0x7, 0xc002be43a0, 0x7, 0x4405, 0x115c9d, 0xc002be0980, ...)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/consensus/replay.go:471 +0x24d
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000a9efb0, 0xa, 0x0, 0xc002be4390, 0x7, 0xc002be43a0, 0x7, 0x4405, 0x115c9d, 0xc002be0980, ...)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/consensus/replay.go:390 +0xe53
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0031a6fb0, 0x13ee440, 0xc0028e6460, 0x13dd860, 0xc0029c6540, 0xc00000e1e0, 0xc000a9ef18)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/consensus/replay.go:270 +0x4a5
github.com/tendermint/tendermint/node.doHandshake(0x13ed0c0, 0xc0028eed20, 0xa, 0x0, 0xc002be4390, 0x7, 0xc002be43a0, 0x7, 0x4405, 0x115c9d, ...)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/node/node.go:303 +0x1b4
github.com/tendermint/tendermint/node.NewNode(0x1b63c60, 0x13d5ae0, 0xc0000b2a00, 0xc000e9fe90, 0x13bd780, 0xc002be6040, 0xc000a0ee80, 0x1275f88, 0xc000a0ee90, 0x13dad60, ...)
	/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/node/node.go:623 +0x310
github.com/pokt-network/pocket-core/app.NewClient(0x1b63c60, 0x13dad60, 0xc000affc00, 0x0, 0x0, 0xc000a9fb68, 0xc000b33260, 0xc, 0xc000b277e0, 0x1b)
	/go/src/github.com/pokt-network/pocket-core/app/tendermint.go:60 +0x649
github.com/pokt-network/pocket-core/app.InitTendermint(0x0, 0xc000010c10, 0x13dad60, 0xc000affc00, 0x0)
	/go/src/github.com/pokt-network/pocket-core/app/config.go:329 +0x109
github.com/pokt-network/pocket-core/app.InitApp(0x7ffd3f024eb1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x7ffd3f024adf, 0x3bd, 0x0, 0x0, ...)
	/go/src/github.com/pokt-network/pocket-core/app/config.go:205 +0x12b
github.com/pokt-network/pocket-core/app/cmd/cli.glob..func52(0x1b00cc0, 0xc0000b9c20, 0x0, 0x5)
	/go/src/github.com/pokt-network/pocket-core/app/cmd/cli/root.go:81 +0xe9
github.com/spf13/cobra.(*Command).execute(0x1b00cc0, 0xc0000b9bd0, 0x5, 0x5, 0x1b00cc0, 0xc0000b9bd0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1b00a20, 0x40a0bf, 0xc000094058, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/pokt-network/pocket-core/app/cmd/cli.Execute()
	/go/src/github.com/pokt-network/pocket-core/app/cmd/cli/root.go:41 +0x2d
main.main()
	/go/src/github.com/pokt-network/pocket-core/app/cmd/pocket_core/main.go:8 +0x20`

Hope the additional context sheds some light on my question about SIGTERM functional support on Pocket.

**Comment by oten91** [comment]
Thanks For you input @thomasdephuoc, can you give us more details about how are you running pocket in the container, 
- is the "GODEBUG=madvdontneed=1" env variable set before starting?
- What container system are you using( docker, kubernetes, openshift? )
- Does this started happening with latest version or with older releases?

**Comment by thomasdephuoc** [comment]
Hi @oten91, there you go

- `GODEBUG=madvdontneed=1` isn't set before starting
- Kubernetes 1.18
- This started happening with Pocket Core 5.2, no issue at all on this front before
- We start pocket with the following command

`  - args:                                                                                                                                                                                                                                                                                                                                                                                                                              
    - pocket                                                                                                                                                                                                                                                                                                                                                                                                                           
    - start                                                                                                                                                                                                                                                                                                                                                                                                                            
    - --mainnet                                                                                                                                                                                                                                                                                                                                                                                                                        
    - --seeds='03b74fa3c68356bb40d58ecc10129479b159a145@seed1.mainnet.pokt.network:20656,64c91701ea98440bc3674fdb9a99311461cdfd6f@seed2.mainnet.pokt.network:21656,0057ee693f3ce332c4ffcb499ede024c586ae37b@seed3.mainnet.pokt.network:22856,9fd99b89947c6af57cd0269ad01ecb99960177cd@seed4.mainnet.pokt.network:23856,f2a4d0ec9d50ea61db18452d191687c899c3ca42@seed5.mainnet.pokt.network:24856,f2a9705924e8d0e11fed60484da2c3d22f7dab
a8@seed6.mainnet.pokt.network:25856,582177fd65dd03806eeaa2e21c9049e653672c7e@seed7.mainnet.pokt.network:26856,2ea0b13ab823986cfb44292add51ce8677b899ad@seed8.mainnet.pokt.network:27856,a5f4a4cd88db9fd5def1574a0bffef3c6f354a76@seed9.mainnet.pokt.network:28856,d4039bd71d48def9f9f61f670c098b8956e52a08@seed10.mainnet.pokt.network:29856,18eaabef85c661344b640b74597c4973af707ccb@pocket-seed.simply-vc.com.mt:26656,5c133f07ed296b
b9e21e3e42d5f26e0f7d2b2832@poktseed100.chainflow.io:26656,361b1936d3fbe516628ebd6a503920fc4fc0f6a7@seed.pokt.rivet.cloud:26656'   `

Hope this helps you re the SIGTERM issue.

Meanwhile we're considering the following corrective measures, I'd be grateful for your take on these:
- launch containers in an interactive manner with TTY
- use an init system such as this one to forward signals: https://github.com/krallin/tini#why-tini https://github.com/krallin/tini

**Comment by andrewnguyen22** [comment]
Thanks @thomasdephuoc This does help a lot in our search for the crux of the issue.

RC-0.5.2.9 requires `GODEBUG=madvdontneed=1` to be set. If you don't set it, the main process spins off a child process with this env variable enabled. This can cause Ctr+c issues no doubt.

**Comment by thomasdephuoc** [comment]
OK we're trying this environment variable setting asap, thank you Andrew.

**Comment by koen84** [comment]
My pokt should be running with `GODEBUG=madvdontneed=1` (is there a way to verify this ?) but when i did systemctl restart yesterday i noticed in the logs it was halting pokt but never managed to, until i `sudo kill -9 $(pidof pocket)`

**Comment by Garandor** [comment]
Anecdotally, I have only ever observed this problem when trying to restart a node that got "stuck".
SIGTERM works fine for me when the node is in normal operation.
I thus believe this issue could be caused by https://github.com/pokt-network/pocket-core-deployments/issues/183
which also means it should be fixed by setting the recommended IN/OUT peers (30:10) in config.json

**Comment by koen84** [comment]
Whatever it is, it's crucial to be fixed.
* SIGKILL could corrupt the pokt db
* Any monitoring would rely on being able to restart correctly, lest not to make things worse instead of better.

**Comment by eddyzags** [comment]
Hey everyone! Jumpin in

I have experienced some problems when running the pocket core on the testnet using the terminal. After stopping the process (ctrl+c), the exit logs appeared but the program didn't exit properly:

<img width="1115" alt="Screenshot 2021-02-20 at 15 00 05" src="https://user-images.githubusercontent.com/1049898/108623290-7aaec300-743e-11eb-91cc-3ced17bf05bb.png">

I am forced hit enter key and then: 

<img width="840" alt="Screenshot 2021-02-21 at 17 30 28" src="https://user-images.githubusercontent.com/1049898/108631521-96c85980-746a-11eb-80f2-5d0f3d936d61.png">



Config used:
* Pocket core version: `RC-0.5.2.9`
* OS version: `Debian Buster x86_64 GNU/Linux 4.19.0-14-cloud-amd64`
* Launch: using terminal

As @andrewnguyen22, this is related to the way the pocket core main process is handling the child process. Everything is closing properly when I set the environment variable to `GODEBUG=madvdontneed=1`. (Lifecycle: The pocket core launches one process, the SIGTERM signal is caught properly, the graceful-stop begins, then the program exits.)
I am curious to know for what purpose we are required to lunch the pocket core in a child process.

Regarding the signal handling issue, I had a deeper look at the pocket core logic and I noticed that the main process isn't waiting for the child process to exit. This can lead to unexpected behaviors while processing the SIGTERM signal in the process group (including parent and child processes). I also assume that the behaviors might differ based on the OS the processes are operating on.
Making the main process wait for the child one to exit could definitely make the pocket core more resilient. I've been working on a fix for that and the pocket core is now responding correctly to ctrl+c. (See the modifications here: #1247 )

**Comment by andrewnguyen22** [comment]
> OK we're trying this environment variable setting asap, thank you Andrew.

Anything new on this @thomasdephuoc ?

**Comment by andrewnguyen22** [comment]
> Hey everyone! Jumpin in
...
> Making the main process wait for the child one to exit could definitely make the pocket core more resilient. I've been working on a fix for that and the pocket core is now responding correctly to ctrl+c. (See the modifications here: #1247 )

@eddyzags @oten91 from our blockchain team commented on your PR, please respond at your convenience

**Comment by andrewnguyen22** [comment]
> Though this problem is offtopic to the current issue, I think my solution to the "checksum mismatch" Problem could be interesting for future reference
> It looks like the data corruption was due to a faulty RAM module. fsck returned nothing unusual so I ran memtest86+ and it returned heaps of errors. Threw out the old RAM module, reran memtest with no failures and now my node exhibits [pokt-network/pocket-core-deployments#183](https://github.com/pokt-network/pocket-core-deployments/issues/183) behavior (i.e. stops roughly every day) but `systemctl restart` does not lead to a corrupted DB anymore (at least so far, even though the restart still happens with SIGKILL after SIGTERM timing out without pocket exiting)

Hey @Garandor any follow up on this, are you still corruption free for the most part?

**Comment by Garandor** [comment]
> Hey @Garandor any follow up on this, are you still corruption free for the most part?

Corruption free since getting rid of the faulty RAM. Node still gets stuck and still doesn't exit on SIGTERM after getting stuck.

**Comment by thomasdephuoc** [comment]
> > OK we're trying this environment variable setting asap, thank you Andrew.
> 
> Anything new on this @thomasdephuoc ?

Hey @andrewnguyen22. The process is gracefully shut down when Pocket core is launched using one process, thanks for the suggestion. cc @eddyzags

**Comment by andrewnguyen22** [comment]
Bump on this issue, any reports / logging that anyone can provide would be very helpful
