### ISSUE TITLE
account-txs cli command ignores the <page> parameter

### ISSUE THREAD

**Issue by krytie07** [pokt-network/pocket-core#1231]
The account-txs cli command seems to ignore the <page> parameter. Running RC-0.5.2.9

For example execute the following to return 10 transactions

```pocket query account-txs 42a8ab1fcdb335da4d5fd0e8ebaa4486bce12acc 1 10 false false```

Reduce the number of results to **1** and set the page parameter to **1** and note the first transaction has a hash of "3DD6721419C5A809D977DB7757B4F3B254C5BED4AAF985C62785C166D2A647F7"

```pocket query account-txs 42a8ab1fcdb335da4d5fd0e8ebaa4486bce12acc 1 1 false false```

Now set the page parameter to **2** and note the transaction returned is still "3DD6721419C5A809D977DB7757B4F3B254C5BED4AAF985C62785C166D2A647F7"

```pocket query account-txs 42a8ab1fcdb335da4d5fd0e8ebaa4486bce12acc 2 1 false false```

I would expect that with the second command as I am only returning 1 transaction at a time and asking for the 2nd page it should be returning the second transaction.

**Comment by andrewnguyen22** [comment]
@edjroz can you verify and loop this in with the Tx Indexer Milestone?
