### ISSUE TITLE
Reduce "MaxNumOutboundPeers" in default config.json by 20%

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1237]
In a peer network of ANY SIZE...

IF MaxIN < MaxOUT all nodes will always be trying to make new outbound connections.
IF MaxIN = MaxOUT the network will try to stabilize in a state with ZERO available incoming slots. 
IF MaxIN > MaxOUT there will always be room for new nodes to join.

I suspect that the current peering difficulties are related to this config parameter.

**Comment by BenVanGithub** [comment]
To add some background and context here...
I spun up 200 brand-new nodes, 
The first 50 synced up and have ZERO stuck/fall behind issues.
The second 50 only had one node get stuck and it cleared up with a restart.
The third 50 had about a 1/3 stuck/fall behind rate, most of them cleared with a restart, some became persistent "trouble nodes"
The last 50 had more than 2/3 stuck/fall behind and would not get caught up and stay caught up without persistent peers assigned.

**Comment by andrewnguyen22** [comment]
> The third 50 had about a 1/3 stuck/fall behind rate, most of them cleared with a restart, some became persistent "trouble nodes"
The last 50 had more than 2/3 stuck/fall behind and would not get caught up and stay caught up without persistent peers assigned.

So @BenVanGithub were you able to alleviate these troubles with a 20% reduction in outbound?

**Comment by BenVanGithub** [comment]
No.  Assigning  a couple it's neighbors as persistent peers fixes it.
Reducing my outbound will help the network a little bit, but have little if any effect on my new nodes.
The whole network needs to move to an IN > OUT to really fix the problem (IMO) 
First step is getting the default value changed.

**Comment by BenVanGithub** [comment]
All any node needs is ONE good peer.
A "good" peer is any node with connectivity to at least 3 other "good" peers.
I have new nodes coming up with 40 peers but they are all bad peers.

**Comment by BenVanGithub** [comment]
Also  regarding inbound connections:  What's up will these seed nodes in-bounding to me and maintaining the connection?
After they have found me, and checked my height, shouldn't they let go?
![Screenshot from 2021-02-11 21-45-29](https://user-images.githubusercontent.com/8411656/107725014-36d7f300-6cb3-11eb-9e8a-b1d956d78c0d.png)

**Comment by andrewnguyen22** [comment]
@BenVanGithub that's a good question. @julio-jimenez can you look into this and ensure they are running in seed_mode?

**Comment by andrewnguyen22** [comment]
I'm comfortable with this change, @BenVanGithub would you advise going 50/30?

**Comment by julio-jimenez** [comment]
> @BenVanGithub that's a good question. @julio-jimenez can you look into this and ensure they are running in seed_mode?

SeedMode is set to true

**Comment by BenVanGithub** [comment]
50 IN / 30 OUT  should ( In my mind ) create plenty of room to breathe. 

If we are in agreement, I'll get started on an upgrade plan for my nodes and we can all start to get the word out via Discord, etc.
Thank you.

**Comment by andrewnguyen22** [comment]
@BenVanGithub yes I think we are in agreement. I wonder if 50 / 30 is too much. Tendermint's original recommendation is 40 / 10. With each extra peer is extra resource consumption.

I would like to see some evidence produced from your nodes that 50 / 30 is a 'more' stable peering config before we pull the trigger.

**Comment by BenVanGithub** [comment]
I'd like to set at:  30 IN / 10 OUT and I will be happy to make the change to every node. It will take a bit of time, because I don't like just fire off shotgun scripts at large percentages of the network.

The effect will be muted and it won't "fix" my machines at any greater effect than it fixes the entire network.
Currently I'm set at 25/25, changing to 30/10 will create 10 slots each which should help.

LMK if we go with this or if you prefer a 40/10 test.  I'm at your service.

**Comment by BenVanGithub** [comment]
And if we get the seed nodes to stop eating the inbound connects it will also help. 
Every node I have gives up at least 5 slots for the seeds.  That alone could be enough to fix things.
![Screenshot from 2021-02-12 17-57-16](https://user-images.githubusercontent.com/8411656/107831450-1a43c580-6d5c-11eb-880c-7f7606417651.png)
Yep.. just did a sample set of 10 nodes.  SimplyStakingSeed is on every one of them and at least 3 pocket-core-seeds as well.
Each seed node must be using up 1,000+ slots!

**Comment by BenVanGithub** [comment]
I have freed up 4,000 slots so far and it looks like pocket's seeds have been fixed as well.

Nodes still fill up with in-bounds as soon as they boot so the network is still hungry, but it is way better than yesterday.

In case anyone wonders how to know the network is hungry.
1.) re-read the very top post.
2.) stop a node, delete it's address book, and restart it.
3.) if the network were not hungry, the in-bound connection would be slow to arrive and the out-bounds would max out immediately.  The opposite is what does occur.  Therefore the network is still short on open inbound connection points.

**Comment by BenVanGithub** [comment]
Update:
I set 400 nodes at in=30, out=10 four days ago.
I have had zero stuck nodes so far.

**Comment by andrewnguyen22** [comment]
Okay so with this evidence, I'm going to change the defaults on RC-0.5.10 to 30/10. Agree?

**Comment by BenVanGithub** [comment]
Yes. I agree that 30/10 should be the default at this time.  If/when further research shows a better ratio, we can change again.  But at this point I'm convinced that this change is a benefit to network health.

**Comment by andrewnguyen22** [comment]
Closed with RC-0.5.10
