### ISSUE TITLE
Load Test Scenario 1

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#1238]
- Document evidence of the Pocket Core 0.6.0 version running in a network with the following characteristics:
    - 5,000 Nodes in the network.
    - Network must be processing upwards of 4,166,666 Relays per session (1 hr sessions).
    - The test must be ran for at least 5 hours (1 session and 1 proof period).

**Comment by andrewnguyen22** [comment]
Closed with tag/RC-0.6.0
