### ISSUE TITLE
Seed nodes maintain connection and used up slots

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1252]
This issue was mentioned and we thought fixed, in #1237 however the plot thickens.

When inbounding to a node....Seed nodes should make connection, then test the connection, then drop the connection.
When receiving connections from a node... Seeds nodes should accept the connection, provide the list and drop the connection.

Almost all of my outbound connections are used up talking to seeds that aren't real peers.
![Screenshot from 2021-02-28 11-23-13](https://user-images.githubusercontent.com/8411656/109426001-2d3fd200-79b9-11eb-86ea-3ab53a600303.png)

**Comment by andrewnguyen22** [comment]
Got it, this might be a good hint for some of the issues we have been seeing

**Comment by andrewnguyen22** [comment]
Interesting finding on this front:

Hard coded in Tendermint
```
SeedMode: config.P2P.SeedMode,
			// See consensus/reactor.go: blocksToContributeToBecomeGoodPeer 10000
			// blocks assuming 10s blocks ~ 28 hours.
			// TODO (melekes): make it dynamic based on the actual block latencies
			// from the live network.
			// https://github.com/tendermint/tendermint/issues/3523
			SeedDisconnectWaitPeriod:     28 * time.Hour,
```

**Comment by BenVanGithub** [comment]
LOL.. That's a nice find!  At least 3 orders of magnitude too long.
