### ISSUE TITLE
[FEATURE REQUEST] pocket query node-rapsheet

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-core#1254]
## Description
Node jailing is a mysterious thing. Often node operators will check their monitoring to find their node is jailed but digging through logs to find the reason is frustrating and sometimes impossible.

## Solution
A new command for the nodes endpoint would be helpful for operators to explore, diagnose, and fix the errors that cause nodes to be jailed, therefore improving the health of the network.

## Alternatives
I've created node monitoring and am working on automatic unjailing but the process can be tricky given the required number of blocks must pass before you can issue the unjail command.

## Desired Output
```pocket query node-rapsheet```

Ouptut:

Ordered set of node jailing history.
Each item in the rapsheet list would include a timestamp, reason, and length of jailing.

**Comment by andrewnguyen22** [comment]
Closed in favor of #1098
