### ISSUE TITLE
Convert output of "get-validator' to lowercase hex

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1268]
Various locations in Pocket (particularly in the config.json) require address strings in lowercase hex in order to function correctly, but none of them produce an error when uppercase is provided.

The most convenient way of acquiring your current validator address is to copy/paste the output of the get-validator command.  If this output was in lowercase hex it would avoid problems.

**Comment by andrewnguyen22** [comment]
Good issue
