### ISSUE TITLE
Payload IDs arent documented

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#127]
Payloads are identified by their ID, but the meaning of each isn't documented outside of the place where they're marshalled/unmarshalled. Maybe we should add this to the protocol documentation? It is possible that the documentation will change a lot between here and MVP/testnet. What do you think?

**Comment by andrewnguyen22** [comment]
I never responded to this, but since MVP doesn't use the messaging protocol and there's only 1 possible Payload ID currently, I think it is safe to backlog this until testnet

**Comment by andrewnguyen22** [comment]
With the introduction of flatbuffers, the schemas (including the payload ids) will be (AOK) held in the source code.
