### ISSUE TITLE
PRs are very atomic, maybe too much so

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#128]
PRs are very atomic at the moment, having two or three of possibly many related issues. This is a bit cumbersome because it means that we get multiple complex rebase scenarios.

Maybe we should group Issues in smaller Projects that are then submitted as a single pull request?
This would also help with code reviews, by making them simpler and not need to be made as often. 

While we're a small team, having a smaller amount of bursts of code checking may be healthier.

**Comment by andrewnguyen22** [comment]
The Pocket Core team has decided to 'meet in the middle' when it comes to PRs. The formalized solution is: if the PR builds upon another PR, then do not create a new PR as this causes a rebase nightmare. Instead, just add it on to the PR pending review. Also, in an attempt to help the developers, the reviewers have decided to not leave a pending PR for longer than a day or two. This way, we will have a quick turnover.
