### ISSUE TITLE
Log level filtering (aka verbosity)?

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#130]
https://github.com/Sirupsen/logrus
```go
log.Trace("Something very low level.")
log.Debug("Useful debugging information.")
log.Info("Something noteworthy happened!")
log.Warn("You should probably take a look at this.")
log.Error("Something failed but I'm not quitting.")
// Calls os.Exit(1) after logging
log.Fatal("Bye.")
// Calls panic() after logging
log.Panic("I'm bailing.")
```

**Comment by andrewnguyen22** [comment]
Unsure what the issue is here? Could you please provide more details when you get a chance!

**Comment by iajrz** [comment]
I mean we should look into verbosity tuning by the time we hit MVP.

**Comment by aqt01** [comment]
Thanks! @iajrz  We implemented logrus on this PR 
https://github.com/pokt-network/pocket-core/pull/441

**Comment by aqt01** [comment]
Sorry, i misunderstand this issue. 

I created this one 
https://github.com/pokt-network/pocket-core/issues/473

With more description and also referencing this one

**Comment by aqt01** [comment]
Closed by 
https://github.com/pokt-network/pocket-core/pull/474
