### ISSUE TITLE
Document API For PC MVP

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#131]
Also maintain a changelog

**Comment by andrewnguyen22** [comment]
An interesting thought. @luyzdeleon @iajrz 

So I have already built an in client reference system for the RPC API.

Meaning if you go to a path at a specific endpoint <localhost:8080/v1/unregister> you get something like this:

````
{
	"endpoint": "localhost:8080/v1/unregister",
	"method": "UnRegister",
	"params": [
		"GID",
		"IP",
		"RelayPort",
		"ClientPort",
		"ClientID",
		"CliVersion",
		"Blockchains"
	],
	"returns": "Success or failure message",
	"example": "curl --data \n{\"GID\":\"string\", \"IP\":\"string\", \"RelayPort\":\"string\", \"ClientPort\":\"string\", \"ClientID\":\"string\", \"CliVersion\":\"string\", \"Blockchains\":[{\"Name\":\"string\", \"NetID\":\"string\", \"Version\":\"string\"}, {struct2}]} localhost:8080/v1/unregister"
}
````

An already formatted *dynamic* JSON response that is a good resource for an in-client guide!

Since it is already in JSON, we should take advantage of that and build a simple JS app that formats the guide (similar to godoc) to show our API endpoints!

**Comment by luyzdeleon** [comment]
> An interesting thought. @luyzdeleon @iajrz
> 
> So I have already built an in client reference system for the RPC API.
> 
> Meaning if you go to a path at a specific endpoint localhost:8080/v1/unregister you get something like this:
> 
> ```
> {
> 	"endpoint": "localhost:8080/v1/unregister",
> 	"method": "UnRegister",
> 	"params": [
> 		"GID",
> 		"IP",
> 		"RelayPort",
> 		"ClientPort",
> 		"ClientID",
> 		"CliVersion",
> 		"Blockchains"
> 	],
> 	"returns": "Success or failure message",
> 	"example": "curl --data \n{\"GID\":\"string\", \"IP\":\"string\", \"RelayPort\":\"string\", \"ClientPort\":\"string\", \"ClientID\":\"string\", \"CliVersion\":\"string\", \"Blockchains\":[{\"Name\":\"string\", \"NetID\":\"string\", \"Version\":\"string\"}, {struct2}]} localhost:8080/v1/unregister"
> }
> ```
> An already formatted _dynamic_ JSON response that is a good resource for an in-client guide!
> 
> Since it is already in JSON, we should take advantage of that and build a simple JS app that formats the guide (similar to godoc) to show our API endpoints!

We can build this maybe using API blueprint https://apiblueprint.org/ and https://github.com/danielgtaylor/aglio to auto-generate the docs.

**Comment by andrewnguyen22** [comment]
See https://github.com/pokt-network/pocket-core-api-doc for development on this front
