### ISSUE TITLE
Optimization to Node/EndBlocker/UpdateTendermintValidators

### ISSUE THREAD

**Issue by oten91** [pokt-network/pocket-core#1313]
@UpdateTendermintValidators

replace
	maxValidators := k.GetParams(ctx).MaxValidators
with
	k.MaxValidators(ctx)

k.GetParams does multiple reads to only return 1 param

Check code for more calls on k.GetParams that uses only 1 param

**Comment by andrewnguyen22** [comment]
closed with c55213c34a90b8895da9cb9196587623e91ddf42
