### ISSUE TITLE
On Each block while handling claimmsgs the First Call to  keeper.GetValidatorsByChain takes 2x - 10x more compared to subsequent calls

### ISSUE THREAD

**Issue by oten91** [pokt-network/pocket-core#1315]

**Comment by oten91** [comment]
![image](https://user-images.githubusercontent.com/3715586/116881596-71d22e80-abf1-11eb-9e17-9376b1148a67.png)

**Comment by edjroz** [comment]
Ill be adding some benchmarks to replicate performance, instead of going by hand

**Comment by oten91** [comment]
![image](https://user-images.githubusercontent.com/3715586/117715570-72953280-b1a6-11eb-8fb9-b08e17e1d452.png)

on latest blocks

**Comment by andrewnguyen22** [comment]
closed with c55213c34a90b8895da9cb9196587623e91ddf42
