### ISSUE TITLE
RC-0.6.3 Test Results

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-core#1317]
### RC-0.6.3 Release Details:

- Return AllClaims if no address is passed to nodeClaims query
- No ABCI query during newTx() function in pocket core module
- Change StdSignature from Base64 to Hex in RPC
- Added config to drop events from account and blocktxs
- New TX Indexer.

## MaxApplications Param:

- Applications cannot stake (no matter what amount) if this parameter is enabled and MaxApplications threshold is reached.
- If an Application unstakes a slot will open up.

## UpdateStake
- _Apps_
	- Applications can up their stake amount (but cannot lessen stake amount)
	- Applications can updated their RelayChains they are staked for
- _Nodes_
	- Nodes can up their stake amount (but cannot lessen stake amount)
	- Nodes can update their service url
	- Nodes can update their RelayChains
        Rules: 
	          1) Must be after upgrade height 
	          2) You should ONLY be able to execute this transaction while status = staked 
	          3) You should be able to execute this transaction while in jail 
	          4) Only can modify certain parts of the structure
	
                    type Application struct {
                        Address                 sdk.Address      // SHOULD NOT CHANGE
                        PublicKey               crypto.PublicKey // SHOULD NOT CHANGE
                        Jailed                  bool             // SHOULD NOT CHANGE
                        Status                  sdk.StakeStatus  // SHOULD NOT CHANGE
                        Chains                  []string         // CAN CHANGE
                        StakedTokens            sdk.BigInt       // CAN GO UP ONLY
                        MaxRelays               sdk.BigInt       // CAN GO UP ONLY
                        UnstakingCompletionTime time.Time        // SHOULD NOT CHANGE
                    }
                    
                    
                    type Validator struct {
                        Address                 sdk.Address      // SHOULD NOT CHANGE
                        PublicKey               crypto.PublicKey // SHOULD NOT CHANGE
                        Jailed                  bool             // SHOULD NOT CHANGE
                        Status                  sdk.StakeStatus  // SHOULD NOT CHANGE
                        Chains                  []string         // CAN CHANGE
                        ServiceURL              string           // CAN CHANGE
                        StakedTokens            sdk.BigInt       // CAN GO UP ONLY
                        UnstakingCompletionTime time.Time        // SHOULD NOT CHANGE
                    }

## Testing and QA considerations:

- Stake should be working as normal. 
- Unstake should be working as normal. 
- Update stake should only work after upgradeHeight (validate that it’s not possible before) 
- Update stake should only work for staked entities. 
- Update stake should still match original rulings.  - If executed a change mid session (while servicing), there are some other behaviors that are expected 
	A) if a node removes that chain from their list they will not get paid for that claim / proof - PASSED
	B) the v1/dispatch sequence should not show the node anymore - PASSED (it’s removed after the session ends tho)
	C) if an app removes the chain from the list, a node should stop servicing the app // this might not be true 
	D) a node should get paid for an app that changed mid session 
	E) If an app updates stake and Max relays the node cannot do more than previous max relays // this might not be true 
	F) if a node changes service url the change should happen right away in the v1/dispatch sequence - Happened in the next block (different than with chain IDs)
- Tendermint’s behavour: 
    - Depending on the stake updated, node/Apps should be removed/added under the same rules, correct?
- Document tests in the testing documentation framework

_If UpdateStake is executed mid session (while servicing), there are some other behaviors that are expected:_

A) If a node removes that chain from their list they will not get paid for that claim/proof
B) The v1/dispatch sequence should not show the node anymore
C) If an app removes the chain from the list, a node should stop servicing the APP
D) A node should get paid for an app that changed mid session
E) If an app updates stake and Max relays the node cannot do more than previous max relays
F) If a node changes service url the change should happen right away in the v1/dispatch sequence

MaxApplications - make sure is enabled after upgradeHeight.
MaxApplications - make sure N quantity of APPs can be staked before the upgradeHeight.
MaxApplications - Enabled - Block new exceeding APPs to stake.
MaxApplications - Enabled and Reached - Unstaking APPs allow new staking APP to be staked.
MaxApplications - Enabled and Decreased - Existing staked APPs remain staked.
MaxApplications - Enabled and Decreased - Existing staked APPs remain staked (if they are greater than maxAPP)
MaxApplications - UpgradeHeight occurs - Existing staked APPs remain staked (if they are greater than maxAPP)

**For more information on test results/details, this spreadsheet stated them:**
https://docs.google.com/spreadsheets/d/1OPzsIxMs6FdxocYujgh_WHs3ohbjNKIHzH0xy8w57Y8/edit#gid=285455087

**For steps by steps and procedural details on each scenario, please refer to the following repo (_in which latest scenarios are still being updated_):**
https://github.com/pokt-network/pocket-core-func-tests

**Attached, please find the setups used for this functional tests execution, plus some test data/evidence on the updateStake scenarios from both, APPs and Nodes, procedures:**

[RC-0.6.0.zip](https://github.com/pokt-network/pocket-core/files/6452944/RC-0.6.0.zip)
[NodeUpdatingResults.txt](https://github.com/pokt-network/pocket-core/files/6452946/NodeUpdatingResults.txt)
[APPsEvidence.txt](https://github.com/pokt-network/pocket-core/files/6452948/APPsEvidence.txt)

**Comment by andrewnguyen22** [comment]
closed with a06fe741f294e2a700839f73c2abefe99fdc8703
