### ISSUE TITLE
RPC query/tx response contains an unnecessary `null`

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-core#1319]
When performing a request to the query/tx with a transaction hash that doesn't exist on the network, the response contains an unnecessary `null` after the JSON response.

`
{"code":400,"message":"tx (5EAE1505666E810F3F67110C680E9673C4859971C4803016D66CE244D23D8DE3) not found"}
null
`

**Comment by oten91** [comment]
fixed on 0.6.3

```
{
    "code": 400,
    "message": "tx (5EAE1505666E810F3F67110C680E9673C4859971C4803016D66CE244D23D8DE3) not found"
}
```
