### ISSUE TITLE
Leveldb LOCK File growing unbounded

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1331]
**Describe the bug**
Reports of 20+GB LOCK files in Application, Session, and Evidence DB on RC-0.6.3 in Linux Machines

Theorized the issue could be related to not closing the databases properly or a dirty shutdown through Pocket Stop command

**Comment by andrewnguyen22** [comment]
```
0.6.3 introduced a new directory structure along with the txindexer 
Somewhere in the legacy code, a database write assumes it is already in the correct directory when it creates a “temporary “ LOCK file.
So the LOCK is getting created in whatever directory the software thinks it is currently working in.
The temporary LOCK never gets removed because it doesn’t exist where the clean up process thinks it should have been created.
The front end failure is “disk full” because of these left over LOCK files.
The strongest pillar for this story is the size of the lock file(s) getting created in some directories (evidence, session) is totally out of scale to the contents of the directory.   === 20 gig of evidence?  20 gig of session? === not possible.
```


Delete Lock File while Pocket is still running and disk space can be reclaimed
Delete Lock File after Pocket is shut down disk space cannot be reclaimed

**Comment by BenVanGithub** [comment]
Contents of LOCK file is the console output.
Possibly something to do with how I'm starting Pocket?
I start it two ways:
1.)  interactive [ pocket start ] and then wait to close the terminal after it is fully initialized
2.)  via script [  pocket start 1>&- 2>&- & ]

000000000000000000000000000000000000000000
nodeuser@an016:~$ head -n75 .pocket/data/application.db/LOCK
I[2021-06-15|02:34:08.919] Starting multiAppConn service                module=proxy impl=multiAppConn
I[2021-06-15|02:34:08.919] Starting localClient service                 module=abci-client connection=query impl=localClient
I[2021-06-15|02:34:08.919] Starting localClient service                 module=abci-client connection=mempool impl=localClient
I[2021-06-15|02:34:08.919] Starting localClient service                 module=abci-client connection=consensus impl=localClient
I[2021-06-15|02:34:08.919] Starting EventBus service                    module=events impl=EventBus
I[2021-06-15|02:34:08.920] Starting PubSub service                      module=pubsub impl=PubSub
I[2021-06-15|02:34:08.920] Starting IndexerService service              module=txindex impl=IndexerService
I[2021-06-15|02:34:08.930] ABCI Handshake App Info                      module=consensus height=28504 hash=5329E02BDE84F308F4EC1EA1EA4EB8F87F7D247732B12227682C48F0D86673A0 software-version= protocol-version=0
I[2021-06-15|02:34:08.930] ABCI Replay Blocks                           module=consensus appHeight=28504 storeHeight=28504 stateHeight=28504
I[2021-06-15|02:34:08.930] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=28504 appHash=5329E02BDE84F308F4EC1EA1EA4EB8F87F7D247732B12227682C48F0D86673A0
I[2021-06-15|02:34:09.060] Version info                                 module=node software=0.33.7 block=10 p2p=7
I[2021-06-15|02:34:09.060] This node is a validator                     module=consensus addr=342722E51507A61BD7080B36AF61CF7A1E76ED69 pubKey=PubKeyEd25519{78FCB995AEA7068EF64A86B31E7629A0336E6C4B95B8E4B1077AB9585E93DB62}
I[2021-06-15|02:34:11.118] P2P Node ID                                  module=p2p ID=342722e51507a61bd7080b36af61cf7a1e76ed69 file=/home/nodeuser/.pocket/node_key.json
I[2021-06-15|02:34:11.118] Adding persistent peers                      module=p2p addrs="[4f73ee7749039aed4e1c6800b46d5853e7ff17e6@an015.benvanman.com:26656 780bbd158c36e27c327c592ecaba7b2b5e58087e@an017.benvanman.com:26656]"
I[2021-06-15|02:34:11.128] Adding unconditional peer ids                module=p2p ids="[4f73ee7749039aed4e1c6800b46d5853e7ff17e6 780bbd158c36e27c327c592ecaba7b2b5e58087e]"
I[2021-06-15|02:34:11.145] Add our address to book                      module=p2p book=/home/nodeuser/.pocket/config/addrbook.json addr=342722e51507a61bd7080b36af61cf7a1e76ed69@134.122.120.170:26656
I[2021-06-15|02:34:11.145] Add our address to book                      module=p2p book=/home/nodeuser/.pocket/config/addrbook.json addr=342722e51507a61bd7080b36af61cf7a1e76ed69@0.0.0.0:26656
I[2021-06-15|02:34:11.145] Starting Node service                        module=node impl=Node
I[2021-06-15|02:34:11.146] Starting P2P Switch service                  module=p2p impl="P2P Switch"
I[2021-06-15|02:34:11.146] Starting Mempool service                     module=mempool impl=Mempool
I[2021-06-15|02:34:11.146] Starting BlockchainReactor service           module=blockchain impl=BlockchainReactor
I[2021-06-15|02:34:11.146] Starting BlockPool service                   module=blockchain impl=BlockPool
I[2021-06-15|02:34:11.147] Starting Consensus service                   module=consensus impl=ConsensusReactor
I[2021-06-15|02:34:11.147] Reactor                                      module=consensus fastSync=true
I[2021-06-15|02:34:11.147] Starting Evidence service                    module=evidence impl=Evidence
I[2021-06-15|02:34:11.147] Starting PEX service                         module=pex impl=PEX
I[2021-06-15|02:34:11.147] Starting AddrBook service                    module=p2p book=/home/nodeuser/.pocket/config/addrbook.json impl=AddrBook
I[2021-06-15|02:34:11.148] Starting RPC HTTP server on [::]:26657       module=rpc-server 
I[2021-06-15|02:34:11.224] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=5
I[2021-06-15|02:34:11.224] Will dial address                            module=pex addr=c6c94b7138313bd4d9560943d3400bbdc008fd56@94.130.178.127:26656
I[2021-06-15|02:34:11.224] Will dial address                            module=pex addr=5fda7a4267239e107e773e3ae735695ae7dbd60d@162.55.48.124:26656
I[2021-06-15|02:34:11.224] Will dial address                            module=pex addr=2b1c4ac291f512ddd6c4441a94fec650ddeb1407@157.230.211.219:26656
I[2021-06-15|02:34:11.224] Will dial address                            module=pex addr=65ffbccd8108cf30e9e6af16d08535bea2151ec9@142.93.1.209:26656
I[2021-06-15|02:34:11.224] Will dial address                            module=pex addr=4b574759cae4fd95a856f10347dd7b5daa1e7f4b@174.138.47.33:26656
I[2021-06-15|02:34:11.224] Dialing peer                                 module=p2p address=4b574759cae4fd95a856f10347dd7b5daa1e7f4b@174.138.47.33:26656
I[2021-06-15|02:34:11.224] Dialing peer                                 module=p2p address=c6c94b7138313bd4d9560943d3400bbdc008fd56@94.130.178.127:26656
I[2021-06-15|02:34:11.225] Dialing peer                                 module=p2p address=5fda7a4267239e107e773e3ae735695ae7dbd60d@162.55.48.124:26656
I[2021-06-15|02:34:11.225] Dialing peer                                 module=p2p address=2b1c4ac291f512ddd6c4441a94fec650ddeb1407@157.230.211.219:26656
I[2021-06-15|02:34:11.225] Dialing peer                                 module=p2p address=65ffbccd8108cf30e9e6af16d08535bea2151ec9@142.93.1.209:26656
I[2021-06-15|02:34:11.228] Saving AddrBook to file                      module=p2p book=/home/nodeuser/.pocket/config/addrbook.json size=292
I[2021-06-15|02:34:11.247] Starting Peer service                        module=p2p peer=4b574759cae4fd95a856f10347dd7b5daa1e7f4b@174.138.47.33:26656 impl="Peer{MConn{174.138.47.33:26656} 4b574759cae4fd95a856f10347dd7b5daa1e7f4b out}"
I[2021-06-15|02:34:11.247] Starting MConnection service                 module=p2p peer=4b574759cae4fd95a856f10347dd7b5daa1e7f4b@174.138.47.33:26656 impl=MConn{174.138.47.33:26656}
I[2021-06-15|02:34:11.258] Added peer                                   module=p2p peer="Peer{MConn{174.138.47.33:26656} 4b574759cae4fd95a856f10347dd7b5daa1e7f4b out}"
I[2021-06-15|02:34:11.514] Starting Peer service                        module=p2p peer=c6c94b7138313bd4d9560943d3400bbdc008fd56@94.130.178.127:26656 impl="Peer{MConn{94.130.178.127:26656} c6c94b7138313bd4d9560943d3400bbdc008fd56 out}"
I[2021-06-15|02:34:11.514] Starting MConnection service                 module=p2p peer=c6c94b7138313bd4d9560943d3400bbdc008fd56@94.130.178.127:26656 impl=MConn{94.130.178.127:26656}
I[2021-06-15|02:34:11.514] Added peer                                   module=p2p peer="Peer{MConn{94.130.178.127:26656} c6c94b7138313bd4d9560943d3400bbdc008fd56 out}"
I[2021-06-15|02:34:11.562] Starting Peer service                        module=p2p peer=5fda7a4267239e107e773e3ae735695ae7dbd60d@162.55.48.124:26656 impl="Peer{MConn{162.55.48.124:26656} 5fda7a4267239e107e773e3ae735695ae7dbd60d out}"
I[2021-06-15|02:34:11.562] Starting MConnection service                 module=p2p peer=5fda7a4267239e107e773e3ae735695ae7dbd60d@162.55.48.124:26656 impl=MConn{162.55.48.124:26656}
I[2021-06-15|02:34:11.562] Added peer                                   module=p2p peer="Peer{MConn{162.55.48.124:26656} 5fda7a4267239e107e773e3ae735695ae7dbd60d out}"
I[2021-06-15|02:34:11.762] Starting Peer service                        module=p2p peer=2b1c4ac291f512ddd6c4441a94fec650ddeb1407@157.230.211.219:26656 impl="Peer{MConn{157.230.211.219:26656} 2b1c4ac291f512ddd6c4441a94fec650ddeb1407 out}"
I[2021-06-15|02:34:11.762] Starting MConnection service                 module=p2p peer=2b1c4ac291f512ddd6c4441a94fec650ddeb1407@157.230.211.219:26656 impl=MConn{157.230.211.219:26656}
I[2021-06-15|02:34:11.763] Added peer                                   module=p2p peer="Peer{MConn{157.230.211.219:26656} 2b1c4ac291f512ddd6c4441a94fec650ddeb1407 out}"
I[2021-06-15|02:34:11.857] Dialing peer                                 module=p2p address=780bbd158c36e27c327c592ecaba7b2b5e58087e@161.35.2.104:26656
I[2021-06-15|02:34:11.866] Starting Peer service                        module=p2p peer=780bbd158c36e27c327c592ecaba7b2b5e58087e@161.35.2.104:26656 impl="Peer{MConn{161.35.2.104:26656} 780bbd158c36e27c327c592ecaba7b2b5e58087e out}"
I[2021-06-15|02:34:11.866] Starting MConnection service                 module=p2p peer=780bbd158c36e27c327c592ecaba7b2b5e58087e@161.35.2.104:26656 impl=MConn{161.35.2.104:26656}
I[2021-06-15|02:34:11.866] Added peer                                   module=p2p peer="Peer{MConn{161.35.2.104:26656} 780bbd158c36e27c327c592ecaba7b2b5e58087e out}"
I[2021-06-15|02:34:12.168] Time to switch to consensus reactor!         module=blockchain height=28505
I[2021-06-15|02:34:12.169] Stopping BlockPool service                   module=blockchain impl=BlockPool
I[2021-06-15|02:34:12.169] SwitchToConsensus                            module=consensus 
I[2021-06-15|02:34:12.807] Dialing peer                                 module=p2p address=4f73ee7749039aed4e1c6800b46d5853e7ff17e6@161.35.122.119:26656
I[2021-06-15|02:34:12.815] Starting Peer service                        module=p2p peer=4f73ee7749039aed4e1c6800b46d5853e7ff17e6@161.35.122.119:26656 impl="Peer{MConn{161.35.122.119:26656} 4f73ee7749039aed4e1c6800b46d5853e7ff17e6 out}"
I[2021-06-15|02:34:12.815] Starting MConnection service                 module=p2p peer=4f73ee7749039aed4e1c6800b46d5853e7ff17e6@161.35.122.119:26656 impl=MConn{161.35.122.119:26656}
I[2021-06-15|02:34:12.815] Added peer                                   module=p2p peer="Peer{MConn{161.35.122.119:26656} 4f73ee7749039aed4e1c6800b46d5853e7ff17e6 out}"
I[2021-06-15|02:34:13.259] Ignoring updateToState()                     module=consensus newHeight=28505 oldHeight=28505
I[2021-06-15|02:34:13.260] Starting State service                       module=consensus impl=ConsensusState
I[2021-06-15|02:34:13.265] Starting baseWAL service                     module=consensus wal=/home/nodeuser/.pocket/data/cs.wal/wal impl=baseWAL
I[2021-06-15|02:34:13.265] Starting Group service                       module=consensus wal=/home/nodeuser/.pocket/data/cs.wal/wal impl=Group
I[2021-06-15|02:34:13.265] Starting TimeoutTicker service               module=consensus impl=TimeoutTicker
I[2021-06-15|02:34:13.265] Searching for height                         module=consensus wal=/home/nodeuser/.pocket/data/cs.wal/wal height=28505 min=7753 max=7841
I[2021-06-15|02:34:13.524] Rejected bad transaction                     module=mempool tx=C5BD98D1AF1ECF85F8609833940C76EDFB7CD1A07DC02DA136100E92BDD83E7B peerID=2b1c4ac291f512ddd6c4441a94fec650ddeb1407 res="&{CheckTx:code:4 log:\"{\\\"codespace\\\":\\\"sdk\\\",\\\"code\\\":4,\\\"message\\\":\\\"ERROR:\\\\nCodespace: sdk\\\\nCode: 4\\\\nMessage: \\\\\\\"signature verification failed for the transaction\\\\\\\"\\\\n\\\"}\" }" err=null
I[2021-06-15|02:34:13.529] Rejected bad transaction                     module=mempool tx=69E2614FF6C9160589000486EB8375453B855D11C709C71C5A34BEB8BA1532FE peerID=2b1c4ac291f512ddd6c4441a94fec650ddeb1407 res="&{CheckTx:code:4 log:\"{\\\"codespace\\\":\\\"sdk\\\",\\\"code\\\":4,\\\"message\\\":\\\"ERROR:\\\\nCodespace: sdk\\\\nCode: 4\\\\nMessage: \\\\\\\"signature verification failed for the transaction\\\\\\\"\\\\n\\\"}\" }" err=null
I[2021-06-15|02:34:13.534] Rejected bad transaction                     module=mempool tx=3EC6B40FCBA7F8B7EB4A827E3E070D2E66B4E9F625B372592D18989ABA0B4D79 peerID=2b1c4ac291f512ddd6c4441a94fec650ddeb1407 res="&{CheckTx:code:4 log:\"{\\\"codespace\\\":\\\"sdk\\\",\\\"code\\\":4,\\\"message\\\":\\\"ERROR:\\\\nCodespace: sdk\\\\nCode: 4\\\\nMessage: \\\\\\\"signature verification failed for the transaction\\\\\\\"\\\\n\\\"}\" }" err=null
I[2021-06-15|02:34:13.538] Rejected bad transaction                     module=mempool tx=B33CC5DCB2621C3606448C9EE819F53FF4D65EEDD2B241B22176B48409AD2D40 peerID=2b1c4ac291f512ddd6c4441a94fec650ddeb1407 res="&{CheckTx:code:4 log:\"{\\\"codespace\\\":\\\"sdk\\\",\\\"code\\\":4,\\\"message\\\":\\\"ERROR:\\\\nCodespace: sdk\\\\nCode: 4\\\\nMessage: \\\\\\\"signature verification failed for the transaction\\\\\\\"\\\\n\\\"}\" }" err=null
I[2021-06-15|02:34:13.539] Could not check tx                           module=mempool tx=C5BD98D1AF1ECF85F8609833940C76EDFB7CD1A07DC02DA136100E92BDD83E7B err="tx already exists in cache"
I[2021-06-15|02:34:13.543] Rejected bad transaction                     module=mempool tx=CD1D9584B4CDCBAF35AF72FF73C8DD382169AA169E8D01238B27889111F5EE99 peerID=2b1c4ac291f512ddd6c4441a94fec650ddeb1407 res="&{CheckTx:code:4 log:\"{\\\"codespace\\\":\\\"sdk\\\",\\\"code\\\":4,\\\"message\\\":\\\"ERROR:\\\\nCodespace: sdk\\\\nCode: 4\\\\nMessage: \\\\\\\"signature verification failed for the transaction\\\\\\\"\\\\n\\\"}\" }" err=null

**Comment by BenVanGithub** [comment]
Confirmed that the growth aspect is/was related to the command that I was using to start pocket.
Suspect that there is still a wierdness with the pocket stop command that is involved.
But I'm calling this issue closed.
Thanks
