### ISSUE TITLE
Possible structural error or embedded corruption in block #30024

### ISSUE THREAD

**Issue by BenVanGithub** [pokt-network/pocket-core#1339]
This curl:

curl -X POST --location "http://127.0.0.1:8082/v1/query/blocktxs"     -H "Accept: application/json"     -H "Content-Type: application/json"     -d '{"height":30024,"page":1,"per_page":1000}'

works correctly when run against blocks 30023 & 30025, but crashes the client and leaves a corrupt walfile when run against 30024.
EDIT:  walfile corruption does not happen every time.

Pocket version RC-0.6.3.6.  
Ubuntu 20.04
Original sync method: unknown (everything I have is a copy of some other node)

**Comment by jorgecuesta** [comment]
I got same issue with my 3 nodes, 2 full nodes and 1 validator. All of them with data from gsutil or 30k backup instructions from RC0.6.3.6 notes.

**Comment by oten91** [comment]
Thanks for the report, currently investigating the issue.

Def Related to #1335
