### ISSUE TITLE
[FEATURE REQUEST] Enforce warning if node staking done with minimum allowed amount (15k POKT)

### ISSUE THREAD

**Issue by vramirez-da01** [pokt-network/pocket-core#1362]
**Is your feature request related to a problem? Please describe.**
CLI 'pocket nodes stake' command accept without warning, if by typo/mistake/misconfiguration/unaware of outcome/lack of knowledge at the moment,  lowest possible amount of 15K POKT if provided. if this is done, will result in almost 100% certainty that staked amount will be burned.

**Describe the solution you'd like**
- Warning indicating high risks of using lowest possible amount. This is present in documentation but a more clear warning/description  may help avoid worst possible situation if enforce at CLI execution. 
- If lowest possible amount used, request at least 1-5  more POKTs with message describing reason for it to give time to node runner/stake entity to properly take corrective actions.

Thanks Vinicio,

**Comment by andrewnguyen22** [comment]
Hello @viraboy thank you for the feature request! It will be highly considered in an upcoming release. Please track this issue for progress :)

**Comment by vramirez-da01** [comment]
Hello @andrewnguyen22 
Thank you for your quick response / feature consideration.
