### ISSUE TITLE
Limit Go Routine creation in Pocket Core

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket-core#1364]
**Description**:

There are some things that consume resources yet are unbounded, like the amount of iterators that can be running at the same time, and those should be bounded to some sane number so that a worst-case scenario won't OOM, just "take longer than it should".

@iajrz describes that there were >200K routines out of which at least 50K were iterator related

**Comment by andrewnguyen22** [comment]
Deferring for release above 8.0
