### ISSUE TITLE
Testnet fails to sync around block 30,000

### ISSUE THREAD

**Issue by dconroy** [pokt-network/pocket-core#1367]
**Describe the bug**
When syncing a testnet validator node from scratch, the data corrupts and will fail around block 30,000

**To Reproduce**
I encountered this bug while running a testnet node with Node Pilot. According to their support they mentioned its actually a pokt issue and not related to Node Pilot

**Expected behavior**
Fully syncing
**Error**
`panic: failed to process committed block (30025:D401BA761E91A1F310E34031CA66FC418F01061EBE88420100D3E4C6E1E24416): wrong Block.Header.AppHash. Expected 517E5DDD80445D367F95A367A7234D3D7F58AFF3EDBCED22D8EAD795491CF723, got AD68480669E8E073C52EA3101B0DF8BB803D88967D224293F7A4703BA29BB18B
1`

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Work Around**
Download the data in advance
wget -O pokt-000.zip https://siasky.net/MAA92V0OzW7UneSk_SOndM_8QSt_ZOegUQZFKsxqKZj_LA

**Comment by OXI-717** [comment]
This is suitable for mainnet too - info: 2021/12/02 14:30:47 error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 687D6E0601A472EFE1A16726F860767568B93BC3AF97A066D44DE426C1F57B30, got 05D0935372CA05A78D64E7BB8C4C63C051224EAAA3177090C5AAF208884C8BC8

**Comment by andrewnguyen22** [comment]
@OXI-717 what version are you using?

**Comment by andrewnguyen22** [comment]
@dconroy I believe this issue was fixed after the node pilot report. Can you confirm if this is still happening?

**Comment by OXI-717** [comment]
> @OXI-717 what version are you using?

Node Pilot v0.8.12

**Comment by auracool** [comment]
This issue is still persisting - pockt node setup NOT node pilot at block 30025 the issue happens
