### ISSUE TITLE
panic: failed to process committed block 28154

### ISSUE THREAD

**Issue by schattingh** [pokt-network/pocket-core#1382]
**Describe the bug**
When syncing a fresh node, pocket crashes with the following error:

```
"POKT"[63705]: "POKT"[63705]: panic: failed to process committed block (28154:CEB4F21E1ACBFE5EFD6D701A48839779D3E27C0EAC3B6A5F7A68FA3417FE1B23): wrong Block.Header.AppHash.  Expected BF34AAEB908D2207A9451F5DC8E15C3439A4D15BCB9CBC631CAE2DFF163B0F53, got 15DE1A44BC72792E0AA016523F461E71298822A000DC2C3057A98E49262FB812
"POKT"[63705]: goroutine 116 [running]:
"POKT"[63705]: github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).processBlock(0x40000e3500)
"POKT"[63705]: #011/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20211022155741-0dc25b2413ec/blockchain/v1/reactor.go:476 +0x5bc
"POKT"[63705]: github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).processBlocksRoutine(0x40000e3500, 0x400057c7e0)
"POKT"[63705]: #011/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20211022155741-0dc25b2413ec/blockchain/v1/reactor.go:335 +0x1bc
"POKT"[63705]: created by github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).poolRoutine
"POKT"[63705]: #011/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20211022155741-0dc25b2413ec/blockchain/v1/reactor.go:374 +0xd4
systemd[1]: pocket.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: pocket.service: Failed with result 'exit-code'.
```

On restart, pocket crashes immediately with the same error

**To Reproduce**

1. Fresh install of RC-0.7.0.1 on Ubuntu 20.04.1 aarch64
2. Install pocket
3. `pocket start --useCache`
4. Allow to sync

**Expected behavior**
Sync should complete successfully

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - n/a

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
Has been reported a number of times on DIscord:

- https://discord.com/channels/553741558869131266/564836328202567725/925488818604376094
- https://discord.com/channels/553741558869131266/564836328202567725/925464688232398868
- https://discord.com/channels/553741558869131266/564836328202567725/920275050123366420
- https://discord.com/channels/553741558869131266/564836328202567725/925490081442193439

**Comment by aimxhaisse** [comment]
I can reproduce this as well (this blocks the [Sandwalker](https://sandwalker.sbrk.org/) as it can't use a snapshot and needs to actually process each block to compute statistics).

**Comment by iajrz** [comment]
Hello! We're looking at the issue at present and were able to reproduce.

**Comment by oten91** [comment]
Hello @schattingh @aimxhaisse 
release 0.7.1 is out and should fix this issue.
https://github.com/pokt-network/pocket-core/releases/tag/RC-0.7.1

Thanks for the reports

**Comment by aimxhaisse** [comment]
Thanks a lot! Trying it out, will post a note here to confirm it went fine :)

**Comment by lekhanhbf121** [comment]
Hhe
