### ISSUE TITLE
More applications than "max_applications"

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1386]
**Describe the bug**
More applications than the set maximum.

When querying `pocket query app-params`, it returns 
```
{
    "app_stake_minimum": "1000000",
    "base_relays_per_pokt": "3509",
    "max_applications": "2045",
    "maximum_chains": "15",
    "participation_rate_on": false,
    "stability_adjustment": "0",
    "unstaking_time": "1814000000000000"
}
```
It says the max_applications is set to 2045, but on pokt.watch and poktscan you can see that there are 2048 apps. 

Note: the docs parameters are not correct https://docs.pokt.network/home/resources/references/protocol-parameters#maxapplications

**Comment by oten91** [comment]
Hello, @DragonDmoney thanks for your report.

The max_applications is a live parameter governed by the DAO, sometimes these changes don't get updated right away on the docs, for this case I have forwarded your report so the current value gets updated.

One important distinction is that, as the parameter description indicates, it defines 

> "The number of **staked** applications that the protocol allows."

The total count of 2048 applications (that pokt.watch and poktscan may be using) includes all the applications including the **unstaked** ones. 

The current numbers are =  [2045 -> staked  and 3 -> unstaked]
