### ISSUE TITLE
Block 30024 Broken

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1387]
**Describe the bug**
`pocket query block-txs 30024` will crash your node.

I discovered this whilst I was syncing POKTwatch, and I believe it has something to do with the chain halt around there or the "OldUpgradeHeight" which you can get by doing `pocket query upgrade`

**Comment by DragonDmoney** [comment]
You guys may have heard about this, but just wanted to make sure you guys are aware.

**Comment by oten91** [comment]
Hello @DragonDmoney , Thanks for your report

It is a known issue and the protocol team is aware and working on a fix for it for the next version (RC-0.8.X).

**Comment by oten91** [comment]
Fixed on RC-0.8.2
