### ISSUE TITLE
Testnet send tx error

### ISSUE THREAD

**Issue by julycanfly** [pokt-network/pocket-core#1388]
network:testnet
desc:send transation error

step 1: imported address
---- EDITED -----

step 2:Enter Encrypt Passphrase

step 3: I use the imported address to transfer
cli:./pocket --remoteCLIURL https://node2.testnet.pokt.network accounts send-tx 10456aa147dce2fa04aea1f2c0152dcd7f039d95 9d224795d2ffbd4b8e6bdd1bb73995faa6cf5c26 1000000 testnet 10000 "" true

step4:Enter Encrypt Passphrase

step5:Return error
https://node2.testnet.pokt.network/v1/client/rawtx
{
    "code": 2,
    "logs": null,
    "raw_log": "{\"codespace\":\"sdk\",\"code\":2,\"message\":\"ERROR:\\nCodespace: sdk\\nCode: 2\\nMessage: \\\"error decoding transaction: proto: illegal wireType 7\\\"\\n\"}",
    "txhash": "18B0C3BA5432A1DF74731598C62517F167502D10036FF5466370B07F29C650DB"
}

**Comment by oten91** [comment]
Hello @leezijie , 
1 - seems you are using an old version of pocket, please do "pocket version" if the version is lower than RC-0.7.0.1, I will suggest upgrading as it is not compatible with the current network state. Current commands do not require the "false" or "true" at the end.

Here is latest https://github.com/pokt-network/pocket-core/releases/tag/RC-0.7.1

Also edited your message as it included a private key import, that's sensitive information, Be sure to not use that account  as anyone that could copy your key have access to the account

**Comment by julycanfly** [comment]
> 

First of all, thank you very much for the warning, but I did the test on testnet.

Then I upgrade pocket to the latest version, and the transaction still fails to be sent. I can guarantee that I have imported the private key to this node.
![image](https://user-images.githubusercontent.com/32590143/151091778-a714b294-1416-4fa1-bd45-3a0f1c4b4062.png)

**Comment by oten91** [comment]
Hello @leezijie,

now you are getting a different error,  "signature verification failed for transaction". 

This could mean 2 things:
Either the node you are using for sending the request with --remoteCLIURL was restarted and has not seen a block, meaning you have to wait about 15 minutes and try to resend

The other case is that the private key you seem to be importing has some issue, you can create a new account from the CLI and confirm if it just fails with the one you are importing.

Read this FAQ about the error 
https://github.com/pokt-network/pocket-core/issues/1172

**Comment by julycanfly** [comment]
> 
@oten91 
Thank you very much. I've taken care of it.

**Comment by toing123** [comment]
@leezijie How do I get pokt in the test network? I understand that it should be obtained from the faucet(https://faucet.pokt.network/), but I find that the official one can't be used

**Comment by julycanfly** [comment]
> @leezijie How do I get pokt in the test network? I understand that it should be obtained from the faucet(https://faucet.pokt.network/), but I find that the official one can't be used
The URL I used before, and it worked back then. Now there may be a problem with the test network. The test network is very unstable. I suggest you buy the mainnet coin directly
