### ISSUE TITLE
ExpiredProofsSubmissionError

### ISSUE THREAD

**Issue by MoonkinCK** [pokt-network/pocket-core#1389]
**Describe the bug**
I have a Claim Tx Failed with the Error `Expired Proofs Submission Error`
The session height is #49117 and tx block is #49139
It clear that this claim was sent too late while the *ClaimSubmissionWindow* is 3 in pocket params.
We have just checked node logs and ensure that our node height was stuck at #49121 over 4 hours. 
> [2022-01-25|20:48:36.108] Executed block                               module=state height=49120 validTxs=400 invalidTxs=3
[2022-01-25|21:03:20.918] Executed block                               module=state height=49121 validTxs=494 invalidTxs=6
[2022-01-26|01:28:10.910] Executed block                               module=state height=49122 validTxs=515 invalidTxs=4

The Server Sys load also went high in that period. 
![image](https://user-images.githubusercontent.com/1916880/151306092-475a8102-3a60-45f2-bcdb-2daddfc7a9e9.png)

But I dont know how this latency failure happened.
Is there any guidelines to handle this problem?

tx hash: 119A54A1AA9F495F527ED94C64641129719130A44AE73A9E3E518ECC0F828FA5

**Comment by oten91** [comment]
Hey @MoonkinCK , seems this has been discussed over discord, let me know if you have additional questions.

**Comment by MoonkinCK** [comment]
> Hey @MoonkinCK , seems this has been discussed over discord, let me know if you have additional questions.

Yep, Thank you guys.
