### ISSUE TITLE
Block-txs returning none right after new block.

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1390]
**Describe the bug**
For a short period after the pocket node block height is updated, when you query block-txs for that block it returns no txs.

**To Reproduce**
Wait for a new block
Instantly query block-txs for that block

**Comment by oten91** [comment]
Hey @DragonDmoney , depending on the hardware capabilities you are using to run pocket and the size of a particular block there is a normal delay between the moment you receive the block and the moment you are able to successfully query information about it (CPU dependant). 

Anecdotally we have seen this time to be in the range from 20 seconds to a full 1-minute delay depending on hardware specs and block content. 

If you are able please let us know if you are seeing something outside this range.

Thanks in advance.

**Comment by DragonDmoney** [comment]
I've realized that, but POKT should return a height that you can query data for. The POKT height should return what the node is synced at.

**Comment by Olshansk** [comment]
Just to make sure I understand, when you run `pocket query height`, it shows you a recently synched block, but when you run `pocket query block-txs <height>`, you get empty responses for ~ 1 min?

**Comment by DragonDmoney** [comment]
> Just to make sure I understand, when you run `pocket query height`, it shows you a recently synched block, but when you run `pocket query block-txs <height>`, you get empty responses for ~ 1 min?

Yes, although I would say its around 10-25 seconds
