### ISSUE TITLE
Log filling with non-actionable entries at "error" log level

### ISSUE THREAD

**Issue by strobus** [pokt-network/pocket-core#1400]
**Describe the bug**
Pocket core outputs dozens of different kinds of non-actionable error logs. This is an issue for anyone running at log level "error" and wanting alarms to trigger when errors happen. The error log needs to be silent unless there is something actionable happening. 

**To Reproduce**
1. Run pocket core as a validator for 1 hour.
4. See errors that are not actionable:
  * `Stopping peer for error      module=p2p peer="..." err="pong timeout"`
  * `Connection failed @ sendRoutine      module=p2p peer=... conn=... err="pong timeout"`
  * `dialing failed (attempts: 1): auth failure: conn.ID (...) dialed ID (...) mismatch module=pex addr=...`
  * `MConnection flush failed    module=p2p peer=... err="write tcp ...`
  * `enterPrevote: ProposalBlock is invalid    module=consensus height=52485 round=0 err="Invalid evidence: evidence was already committed. Evidence: VoteA: ...`
  * Items mentioned at [Errors in Logs](https://docs.decentralizedauthority.com/advanced/troubleshooting/pocket/errors-in-logs)

**Expected behavior**
Nothing should be logged at error level when expected conditions occur. These should be logged as warning or informational logs.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Olshansk** [comment]
@strobus Thanks for bringing this up.

I completely agree and just wanted to point out that some of this is legacy that we've inherited from tendermint. For example:
* `dialing failed (attempts: 1): auth failure` was also flagged in [tendermint/issues/3716](https://github.com/tendermint/tendermint/issues/3716)
* `Connection failed @ sendRoutine` was also flagged in [tendermint/issues/4925](https://github.com/tendermint/tendermint/issues/4925)

This is not something the core team currently has bandwidth to handle but PRs are welcome!

**Comment by strobus** [comment]
Sure, I can take a look. It looks like pocket-core is using its own fork of tendermint? Is that refreshed regularly from upstream? https://github.com/pokt-network/pocket-core/blob/5b14920eb5aa0eeea2e0c48b573c6ff7e8cee18c/go.mod#L30
