### ISSUE TITLE
eth_getLogs not working (polygon archival)

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1402]
**Describe the bug**
Polygon Archival Event logs unsupported

eth_getLogs throws an error whenever it is queried.

Error: processing response error (body="{"jsonrpc":"2.0","id":44,"error":{"message":"Internal JSON-RPC error.","code":-32603}}", error={"code":-32603}, requestBody="{"method":"eth_getLogs","params":[{"fromBlock":"0x1788271","toBlock":"0x1791bc5","address":"0x5430a0b6c11f870571ffa891d59dec8c4608ea9a","topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0x0000000000000000000000000000000000000000000000000000000000000000"]}],"id":44,"jsonrpc":"2.0"}", requestMethod="POST", url="", code=SERVER_ERROR, version=web/5.6.0)

**Comment by oten91** [comment]
External chain issue, no actionable from the pocket core side.
