### ISSUE TITLE
Polygon nodes completely out of sync

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1403]
**Describe the bug**
I know that due to Polygon's nature, some nodes may fall 1-10 blocks behind, but some nodes are over 3000+ blocks behind, and it is not consistent.

**To Reproduce**
```
python3
>>> from web3 import Web3
>>> w3 = Web3(Web3.HTTPProvider("https://poly-archival.gateway.pokt.network/v1/lb/*********"))
>>> w3.eth.block_number
26022230
>>> w3.eth.block_number
26025267
```

For reference, this is my unaltered (except for gateway key) command line usage.

The actual polygon block (polygonscan) was 26025328

**Comment by DragonDmoney** [comment]
I would decrease the max block difference that the gateway allows to prevent this.

**Comment by oten91** [comment]
External chain issue, no actionable from pocket core side
