### ISSUE TITLE
Pocket query nodes times out

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1406]
**Describe the bug**
If you set up a POKT node following the exact directions by the docs and try 'pocket query nodes' the node will time out and give you no results. This happens even if you set the max per page to 1. You can fix this issue by increasing the RPC timeout, but most users do not know that.

**Comment by DragonDmoney** [comment]
IMO all functions in pocket-core should be usable without extensive configuration.

**Comment by bashiru98** [comment]
facing same issue so how can one increase the rpc timeout any sample? @DragonDmoney

**Comment by DragonDmoney** [comment]
> 

"pocket_config": {
......
"rpc_timeout":10000
....
}

the timeout time is in ms so divide by 1000 to get seconds

*for default installations this file is in ~/.pocket/config/config.json
