### ISSUE TITLE
Why does synchronization get slower and slower

### ISSUE THREAD

**Issue by julycanfly** [pokt-network/pocket-core#1407]
I started the node as a snapshot, which was fine for a while, but after a while the node synchronization slowed down.Then the height of the block from other network nodes is more and more different.
![telegram-cloud-photo-size-5-6185857881522417339-y](https://user-images.githubusercontent.com/32590143/159828927-d660bfff-c5e1-4c23-9cd1-927e17801448.jpg)
This is the relevant log, and such a log will last for a long time with no other output.
There is no synchronization block information in the log.
Why does this happen, and what can I do about it.

**Comment by julycanfly** [comment]
And when I restart pocket service, its RPC port will even be exposed after 10 minutes.

**Comment by 7-of-9** [comment]
+1 -- this is becoming borderline useless. Cannot sync, even from snapshot. 3 nodes sync'd to same snapshot, after ~48 hours none of them are fully sync'd.

**Comment by julycanfly** [comment]
I don't even dare to restart the service now.If your node is not of the latest height, broadcast signed transactions and will not return txHash. Amazing

**Comment by DragonDmoney** [comment]
I've synced nodes recently without too many issues (from snapshot) it could be a hardware issue.

What are the specs of the machines?

**Comment by julycanfly** [comment]
> I've synced nodes recently without too many issues (from snapshot) it could be a hardware issue.
> 
> What are the specs of the machines?

16c 32g 2T,ulimit 100000,Isn't that enough?

**Comment by 7-of-9** [comment]
I've also played about with all kinds of HW profiles (Azure VMs), including boosted SSDs. No dice.

Sync is broken AF.

**Comment by julycanfly** [comment]
Improvements have been made since version rc-0.8.2
