### ISSUE TITLE
Resolve InvalidBlockHeightError and inefficiencies in relay processing at block commit time

### ISSUE THREAD

**Issue by strobus** [pokt-network/pocket-core#1410]
**Describe the bug**
When an app submits a relay request, the included Proof contains the block height (presumably the current block height from the client's perspective). When this relay request hits a validator/servicer node just after the block commit, the block height is now incremented by 1. Therefore the Proof contains the "wrong" block height and the InvalidBlockHeightError is thrown [here](https://github.com/pokt-network/pocket-core/blob/d2ae3f8e28acf7f829fd0bf38b8a19e3bae9e3a4/x/pocketcore/types/service.go#L45-L48). An HTTP status code of 499 is returned to the app.

**To Reproduce**
1. Launch and stake a validator/servicer node.
2. Wait for a session to start with relays being sent to the node.
3. Monitor the node block height.
4. When the block height increments by 1, check the nodes error log. The following error is thrown for each relay request in which the app created it's Proof for the previous block:
```
Mar 30 03:41:17 hostname pocket-core[486646]: E[2022-03-30|03:41:17.432] could not validate relay for app: ea8bd90ccbba42ed5b4e95d80758204e7f59be30240ac40b8dbbeb743deba668 for chainID: 0009 with error: ERROR:
Mar 30 03:41:17 hostname pocket-core[486646]: Codespace: pocketcore
Mar 30 03:41:17 hostname pocket-core[486646]: Code: 60
Mar 30 03:41:17 hostname pocket-core[486646]: Message: "the block height passed is invalid"
Mar 30 03:41:17 hostname pocket-core[486646]:
```
5. Wait for a couple other sessions and observe that this issue occurs for any relay chain.
6. Note in the nginx logs that the HTTP response status code sent to the app is 499.

**Expected behavior**
App relays are processed efficiently and quickly by the first node that receives them. Validator/servicer does not get sent relays that it cannot process.

I think this can be improved but would like to discuss some strategies. 
  a. Revise the RPC API to allow a value of "next_available" to be used in the block height field [here](https://github.com/pokt-network/pocket-core/blob/5b14920eb5aa0eeea2e0c48b573c6ff7e8cee18c/doc/specs/rpc-spec.yaml#L127).
  b. Allow a 1-block tolerance in the Proof check [here](https://github.com/pokt-network/pocket-core/blob/d2ae3f8e28acf7f829fd0bf38b8a19e3bae9e3a4/x/pocketcore/types/service.go#L46).

I am not sure if these strategies have downstream effects on Claim and Proof transactions submitted by the node.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Pocket-core version RC-0.7.1

**Comment by byoung0589** [comment]
Note: This is also occurring on BETA-0.8.0

**Comment by nodiesBlade** [comment]
I think the block height check is intentional as per [docs](https://docs.pokt.network/home/v0/protocol/servicing#metadata) to prevent client synchronization attacks. But to be honest, I have no idea what that means. Could someone from Core elaborate?
