### ISSUE TITLE
[FEATURE REQUEST] Manual claim and proof submission 

### ISSUE THREAD

**Issue by breezytm** [pokt-network/pocket-core#1411]
**Is your feature request related to a problem? Please describe.**
Currently, the pokt software is configured to automatically submit both claims and proofs. There are times when the first attempt to submit a proof fails and node runners are obligated to wait for the next time the node re-submit the proof. This makes it extremely difficult to perform any sort of maintenance that requires a shutdown and/or restart. 

**Describe the solution you'd like**
I want a non-trivial **manual claim and proof cli submission param** that allows us to attempt to submit proofs. Perhaps a mechanism can be put in place that prevents any abuse.

**Comment by ZaatarHerb** [comment]
I support this enhancement for the reasons given.

**Comment by petersian2** [comment]
I strongly agree! This has been a problem. Breezy makes a good point

**Comment by computa** [comment]
I fully support this feature. 
I myself have had this issue many times over. 
I will be happy if this was implemented.

**Comment by amehrdad88** [comment]
I support this too, would make managing the process a lot better

**Comment by theutsav** [comment]
I strongly support  this request. Would make our life much much easier.
