### ISSUE TITLE
[BUG] Failing to submit proofs 

### ISSUE THREAD

**Issue by breezytm** [pokt-network/pocket-core#1412]
**Describe the bug**
Recently a couple of node runners, including myself, have reported their nodes are failing to submit proofs until the claim expiration blocks are reached. When using the ``query node-claims <address>``command, it shows the proofs are still there until they are expired. 

Here are a few collected screenshots 

![image](https://user-images.githubusercontent.com/3412923/161849900-2428c5f4-fad6-4a48-9535-1ed02da1fcb3.png)

![image](https://user-images.githubusercontent.com/3412923/161850396-858a6b93-2cf8-40ac-8ea1-4332c3230c14.png)

**Comment by aidin3000** [comment]
This issue really has started to creep up lately. Have made no changes in resources allocated for months.

**Comment by schattingh** [comment]
Had a similar issue submitting a proof, with the error, `Invalid Merkle Verify Error`, and with a `tx_result` code of 66.

The tx hash for reference is `IF9A00DBD631820E9DCF11E07132C492585969C030D2FE3C36D7CEA6D57146FC9`

**Comment by theutsav** [comment]
I have so many of them as well like two below:

<img width="1209" alt="Screen Shot 2022-04-06 at 2 49 10 pm" src="https://user-images.githubusercontent.com/1947015/161898108-68ca4e30-1a0f-401a-b3bc-db3c18153002.png">

<img width="1209" alt="Screen Shot 2022-04-06 at 2 53 06 pm" src="https://user-images.githubusercontent.com/1947015/161898433-f9eb5e07-f88d-48fc-863c-e8ab58942056.png">

**Comment by computa** [comment]
I have so many of this issue lately. This needs to be fixed. 

<img width="1426" alt="Picture 1" src="https://user-images.githubusercontent.com/12607843/161936409-f04f01c7-f098-403b-a308-59300241b58f.png">

**Comment by luyzdeleon** [comment]
Hello @breezytm and everyone else who contributed evidence to this issue, we are currently actively investigating this and will use this issue to gather evidence about a potential issue with the Claim and Proof lifecycle, stay tuned to this issue as we uncover more and analyze the code to request specific information from you so we can get to the bottom of this.

**Comment by mmartinez** [comment]
Happened today for me as well:
![image](https://user-images.githubusercontent.com/2624124/164462308-1cee7bf5-49fc-4873-8a86-68a902800060.png)

**Comment by oten91** [comment]
This appears to have stopped after the release of 0.8.X. Can You guys confirm? @mmartinez @breezytm @computa  @schattingh @aidin3000

**Comment by breezytm** [comment]
I have not had this issue since v0.8.x implementation.

**Comment by mmartinez** [comment]
Same here, no issues with the new version.
