### ISSUE TITLE
Mainnet fails to sync at block 57562

### ISSUE THREAD

**Issue by Amaiyeye** [pokt-network/pocket-core#1419]
I[2022-04-28|05:09:54.635] Initializing pocket core config              
I[2022-04-28|05:09:54.645] Initializing ctx cache                       
I[2022-04-28|05:09:54.645] Initializing pos config                      
I[2022-04-28|05:09:54.645] Initializing app config                      
I[2022-04-28|05:09:54.645] Initializing genesis file                    
I[2022-04-28|05:09:54.645] Initializing Tendermint                      
I[2022-04-28|05:09:55.788] Starting multiAppConn service                module=proxy impl=multiAppConn
I[2022-04-28|05:09:55.788] Starting localClient service                 module=abci-client connection=query impl=localClient
I[2022-04-28|05:09:55.788] Starting localClient service                 module=abci-client connection=mempool impl=localClient
I[2022-04-28|05:09:55.788] Starting localClient service                 module=abci-client connection=consensus impl=localClient
I[2022-04-28|05:09:55.788] Starting EventBus service                    module=events impl=EventBus
I[2022-04-28|05:09:55.788] Starting PubSub service                      module=pubsub impl=PubSub
I[2022-04-28|05:09:55.788] Starting IndexerService service              module=txindex impl=IndexerService
I[2022-04-28|05:09:55.788] ABCI Handshake App Info                      module=consensus height=57562 hash=D66613A2CB9414F198509D83040DCFC94F01A2216DB84B082B3B4ECEF46C1DFC software-version= protocol-version=0
I[2022-04-28|05:09:55.788] ABCI Replay Blocks                           module=consensus appHeight=57562 storeHeight=57563 stateHeight=57562
I[2022-04-28|05:09:55.788] Replay last block using real app             module=consensus 
2022/04/28 05:09:55 error during handshake: error on replay: wrong Block.Header.NextValidatorsHash.  Expected 2D530E6C0817A5CF52578AF9F873C1D437BC242DCE0DA15F50F80A218337460A, got 5F079B522E5D0FCD0E69DF9F859FF5A959EA3EBF99DF4C0C77B9A35D1A6965C3

**Comment by oten91** [comment]
If you were not running RC-0.8.2 by block 57561 your data is most likely corrupted, please use the latest snapshot https://pocket-public-blockchain-snapshots.s3-accelerate.us-east-2.amazonaws.com/pokt/pocket-57705.tar 
 and make sure to use the latest release https://github.com/pokt-network/pocket-core/releases/tag/RC-0.8.2
