### ISSUE TITLE
Sort on v1/query/accounttxs RPC endpoint not working 

### ISSUE THREAD

**Issue by schattingh** [pokt-network/pocket-core#1420]
Version RC-0.8.2

Toggling sort between asc/desc does not seem to alter the order of returned transactions on the `v1/query/accounttxs` RPC endpoint.

To reproduce:

```
curl -s -XPOST --data '{"address": "<address>", "height": 0, "page": 1, "per_page": 10,"sort": "asc"}' \
  http://<pocket-node>/v1/query/accounttxs | jq ' .txs | .[].height'
```
vs

```
curl -s -XPOST --data '{"address": "<address>", "height": 0, "page": 1, "per_page": 10,"sort": "desc"}' \
  http://<pocket-node>/v1/query/accounttxs | jq ' .txs | .[].height'
```

In my case, running the two commands above result in the same ascending order of returned transactions

**Comment by oten91** [comment]
We have identified an error on the example on the rpc-spec.yaml,  Please use "order" instead of "sort" on the request.
