### ISSUE TITLE
metrics for `pocketcore_service_tokens_earned_for_` is not the  amount of token earned

### ISSUE THREAD

**Issue by larryhere** [pokt-network/pocket-core#1428]
After reviewing the metrics code, I found that the `pocketcore_service_tokens_earned_for`  counted the number of tokens obtained, which was inconsistent with the amount specified in the document.

The doc:
https://github.com/pokt-network/pocket-core/blob/staging/doc/specs/metrics.md

If we need to count the revenue of nodes, can we add this to metrics?

**Comment by nodiesBlade** [comment]
https://github.com/pokt-network/pocket-core/blob/a4546978064f7363cf1afa0bf2626514a590c6d6/x/pocketcore/types/metrics.go#L190 it's because upoktearned isn't being used and it only increments by 1
