### ISSUE TITLE
Configurable AuthToken Generation

### ISSUE THREAD

**Issue by oten91** [pokt-network/pocket-core#1447]
Currently pocket-core creates a random new AuthToken on start, users would like to have the token creation be configurable so they can reuse the same tokens for all their nodes.

See [InitAuthToken](https://github.com/pokt-network/pocket-core/blob/a4546978064f7363cf1afa0bf2626514a590c6d6/app/config.go#L871)

- [x] Add Config to pocket_config on config.json
- [x] Make token generation / loading based on the configuration of the node and existence of the token file (auth.json)

**Comment by addiaddiaddi** [comment]
What would be the benefit of this? What actions require the auth token?

**Comment by jbroudou** [comment]
+1 on this. Having a token that auto regenerates on every restart limits the opportunity to create useful automation scripts.

**Comment by jorgecuesta** [comment]
> @addiaddiaddi 

this help a lot for automation on things like for example control resources of the node and when a threshold is rich, using that token u can for example stop the node. After that your automation tool could start it again.

Other case is to automate things like update chains and/or check chains after an update.
