### ISSUE TITLE
Unstake node 

### ISSUE THREAD

**Issue by qywang2012** [pokt-network/pocket-core#1452]
**Describe the bug**
I am having problems unstaking a node.
AppVersion: RC-0.8.2

**To Reproduce**
I use the pocket-js(RC-0.9.1) to send the nodeUnstake tx, it cannot work.
https://github.com/pokt-network/pocket-js

Then I use the cli cmd:
pocket nodes unstake [address] [address] mainnet 10000 true

The tx submit success.

My question is:
How long does the node receive the pledged token after it begins unstake ？
Do I need additional operations to take this pledge fee？

**Comment by oten91** [comment]
Hello @qywang2012 see a similar issue https://github.com/pokt-network/pocket-core/issues/1451 . 

Unstaking time is 21 days. 

To be able to help you further we will need the node address and tx hash of the failed txs.

**Comment by qywang2012** [comment]
Thanks the response!
