### ISSUE TITLE
LeanPOKT Documentation

### ISSUE THREAD

**Issue by oten91** [pokt-network/pocket-core#1469]
Pending LeanPOKT Documentation

@PoktBlade Please update the CLI docs with command etc. information about how to use Lean Pocket for node runners: https://github.com/pokt-network/pocket-core/tree/staging/doc/specs/cli

**Comment by oten91** [comment]
@PoktBlade This is the issue to track the Documentation PR

**Comment by jessicadaugherty** [comment]
Requesting updates to the CLI specification document here: https://github.com/pokt-network/pocket-core/tree/staging/doc/specs/cli 

Keep us posted @PoktBlade and let us know if you have any questions or need more info!

**Comment by nodiesBlade** [comment]
https://github.com/pokt-network/pocket-core/pull/1488 done
