### ISSUE TITLE
[REQUEST FOR PROPOSALS] Allow changing the output address

### ISSUE THREAD

**Issue by nodiesBlade** [pokt-network/pocket-core#1499]
**Please explain the goal of the RFP.**

Allow users to change their non-custodial wallet address

**Please provide a justification for your RFP.**

Couple reasons

- Non custodial was designed back in 2021 where upstaking (per PIP-22) did not exist. Legacy accounts cannot upstake without deciding on whether they want to be non custodial or custodial **forever**. This was not a planned side effect.
- Insurance purposes - insurance providers (coincover) have not decided whats their policy around non custodial and the best security practices for this (1 to ..n output wallets?). Node runners are now at a dilemnia on whether they should upstake a node and forever be custodial, or set to non custodial without following guidelines.
- In the event the non-custodial account private keys get exposed, there is no way to mitigate the issue.
- In general, keys should be rotatable.

**Please provide success criteria for proposals responding to this RFP.**
- Users who have access to the output address private keys can change the output address through another stake tx.

**Add aditional context regarding this RFP.**

I did some initial scoping for this - it seems to be a small change in general. 

https://github.com/pokt-network/pocket-core/blob/staging/x/nodes/keeper/valStateChanges.go#L233, here we will need to add a clause to check if the signer address was equal to the old output address

Most of the leg work will be in testing.

**Comment by Olshansk** [comment]
Completed as part of the latest release: https://github.com/pokt-network/pocket-core/releases/tag/RC-0.10.3
