### ISSUE TITLE
[Documentation] V0 Knowledge Transfers

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket-core#1504]
## Objective

Disseminate V0 knowledge to the broader protocol team.

## Origin Document

[Knowledge Transfer Requests](https://www.notion.so/pocketnetwork/Protocol-Team-83ea53817a944b99a6b5ec2d366a3b57)

## Goal

- Document key V0 functionality to present to the team and reference that covers:
   - Forcing Tendermint into specific states
   - Triaging corrupted DBs
   - Persistence Replacement Review to date
   - Misc. Node Running FAQs
      - The claim and proof lifecycle
      - Pocket’s profiling mode endpoint (e.g. given chain ID → get # of nodes stacked)
      - How hostname resolution works with Geomesh

## Deliverable

- Provide an example PR of how to force Tendermint into a specific state 
- Instructions on determining if/how the db is corrupted 
- An overview of block size experiments that have been started
- A step-by-step of how persistence replacement was reviewed
- Workshop/Document on Node Running FAQs
   - Claim/Proof lifecycle [presentation](https://docs.google.com/presentation/d/1ftD1B_HTah1rzcO2yOqVZLsPtmIKKWunoAm7WvDpFPQ/edit#slide=id.g174e04bf4f3_0_176)
   - How to use the profiling mode endpoints
   - Example(s) of how hostname resolution works with Geomesh
- Attach all the above deliverables to this issue

## Non-goals / Non-deliverables

- Formally documenting in code

---

**Creator**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
Presentations: https://drive.google.com/drive/folders/1t-t0n7uMyvx-wBraDWBKVRLh532ZfD-c

**Comment by oten91** [comment]
- Provide an example PR of how to force Tendermint into a specific state:
  - https://github.com/pokt-network/tendermint/tree/directToRound
- Instructions on determining if/how the db is corrupted
  - https://docs.google.com/presentation/d/1swFg6pzJSKXz9JnWkoQx5NegPnzuDWHnS4s25t7djt8/edit?usp=share_link
- A step-by-step of how persistence replacement was reviewed
  - https://www.notion.so/pocketnetwork/Release-0-9-3-Guide-dfaf1d7182134cf0aa3b6f92ba1fdcd3
- Workshop/Document on Node Running FAQs
  - https://docs.google.com/presentation/d/1ftD1B_HTah1rzcO2yOqVZLsPtmIKKWunoAm7WvDpFPQ/edit?usp=share_link
  - https://www.notion.so/pocketnetwork/Debug-mode-Tips-cd678a46c33244b5860f2b177561f859
  - https://www.notion.so/pocketnetwork/Node-Knowledge-Dissemination-f30dec375b384699a151b5095a9dfddc#0612ddac28754d1a94693eafaee00565

**Comment by oten91** [comment]
- An overview of block size experiments that have been started
  - No specific experiments carried out yet, feature was tested for the 0.9.0 release.

**Comment by oten91** [comment]
@jessicadaugherty let me know if you need anything else
