### ISSUE TITLE
Document v0 Snapshot Details

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket-core#1562]
# Origin Document

https://forum.pokt.network/t/allocated-priority-mainnet-snapshots/4502/2

## Deliverables

- [ ] Add a new document under [docs](https://github.com/pokt-network/pocket-core/tree/staging/doc) documenting everything related to managing and accessing the snapshot
- [ ] Update the main [README](https://github.com/pokt-network/pocket-core/blob/staging/README.md) with a link pointing to the document above

**Comment by Andrew-Pohl** [comment]
Thanks @Olshansk I will sort this tomorrow morning

**Comment by Olshansk** [comment]
Completed here: [doc/guides/snapshot.md](https://github.com/pokt-network/pocket-core/blob/staging/doc/guides/snapshot.md)!
