### ISSUE TITLE
Document v0 TestNet

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket-core#1563]
# Origin Document

https://forum.pokt.network/t/infrastructure-support-testnet-experiment/4092/3

## Deliverables

- [x] Add a new document under [docs](https://github.com/pokt-network/pocket-core/tree/staging/doc) documenting everything related to managing and accessing TestNet
- [x] Update the main [README](https://github.com/pokt-network/pocket-core/blob/staging/README.md) with a link pointing to the document above

**Comment by StevenMartinez94** [comment]
please check https://github.com/pokt-network/pocket-core/pull/1569
