### ISSUE TITLE
Periodically read from the database (dynamodb)

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#174]
@luyzdeleon @iajrz any idea how often we want this to happen?

**Comment by iajrz** [comment]
I'd make it configurable, just in case. Sane initial default guess, maybe once every 5 minutes.

**Comment by andrewnguyen22** [comment]
Also, I should probably add a dispatcher flag to our setup right? To allow us to enable this setting

**Comment by iajrz** [comment]
Of course :) that should only run if the node is a relay node.
