### ISSUE TITLE
Run tests in Dockerfile

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#191]
Add the `go test` command to run unit tests in the `Dockerfile`.

This couldn't be done in #189 because of credentials dependencies that need to be configured at build time.

**Comment by andrewnguyen22** [comment]
Can we document why this isn't implemented in #189 ?

**Comment by luyzdeleon** [comment]
> Can we document why this isn't implemented in #189 ?

Done

**Comment by aqt01** [comment]
Can we close this Or is there something left?
