### ISSUE TITLE
Add `host` attribute to HostedChain struct

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#201]
HostedChain struct: https://github.com/pokt-network/pocket-core/blob/mvp-staging/node/chain.go#L24

1. Add a `host` attribute to struct.
2. Parse the `host` attribute from chains.json

**Comment by andrewnguyen22** [comment]
^^ I think you mean host attribute

**Comment by andrewnguyen22** [comment]
Edited description and title to reflect `host` and not `port`
