### ISSUE TITLE
Return current block hash 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#202]
**Service Node Suggestion:**

Can we add a feature to where the node returns a current block number when a user get current health status along with the tx hash(when i send a tx)?

**Comment by andrewnguyen22** [comment]
(Assuming you are referring to Pocket Network Block Number...) Yep, these kinds of QOL features were always going to be added in production. However, considering this is a feature that will likely be implemented (8-10) months from now and not for MVP, I will close this for now.
