### ISSUE TITLE
Document the process to get a GID

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#220]
Prospect developers and participants in pokt will want to know how to get credentials to be part of the pokt network MVP release. The process to get a GID and participate should be documented and referred to from the README.md file.

**Comment by andrewnguyen22** [comment]
Right, so the GID process is currently centralized and will be explained in the MVP webpage. As for production, GID process is currently undefined.

**Comment by andrewnguyen22** [comment]
@luyzdeleon do you consider this something that needs to be in README of MVP?

**Comment by iajrz** [comment]
@andrewnguyen22 the issue exists because I think _at least a link_ to the explanation should be in the MVP README.md :^) I think README isn't complete if people don't know how to get in.
