### ISSUE TITLE
Explaining MVP vs Core

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#221]
It is important for prospect users and contributors to understand where we stand on the development, and how to get involved. Having information about the status of development, the `staging` vs `mvp-staging` branches and their meaning in the overarching path we're following is crucial.

Possibly the README isn't the best place to lay it all out, but a quick intro with a link to further information would go a long way.

We should also explain the `mvp-staging` vs `staging` in the Developer Setup Guide.

We should document that for MVP the dispatch functionality will not be widespread.

**Comment by andrewnguyen22** [comment]
Marketing is working on a webpage for MVP. Once this is complete, we will be able to use some of their materials to sync w/ the github ;)
