### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket-core#222]
It's important, to avoid confusion, to point people at the [Developer Setup Guide](https://github.com/pokt-network/pocket-core/wiki/Developer-Setup-Guide) earlier in the README.md; reading through the document tempts one to tinker before having all the information; this would be OK if the steps yielded a running app, alas, they don't.

We should consider reorganizing the Developer Setup Guide. The "quick start" commands can be at the beginning, and the details at the end, yielding a natural progression for the curious and an easy startup for those in a hurry.

We should consider organizing the command documentation in a way more reminiscent of what you'd find any day in the command line. Grouping them by function would also help developers map the commands to what they want to do faster.

**Comment by andrewnguyen22** [comment]
I don't have any problem with this. @luyzdeleon initially designed the dev guide so I'd like to hear his input

**Comment by jeremybeal11** [comment]
@iajrz  i can assist in cleaning it up. I'm working on my first setup with PocketCore and i can leave some useful notes to help out.

**Comment by iajrz** [comment]
It was left open on purpose ;) some of this applies to Core. Thanks for keeping things tidy :)
