### ISSUE TITLE
Wrong command in the docker-compose Readme

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#355]
@aqt01,  the [readme](https://github.com/pokt-network/pocket-core/tree/mvp-master/docker-compose#pocket-core-config-by-volume-mappingyml) has the mapping command at:

**docker-compose -f pocket-core-config-by-s3.yml up**

when it needs to be:

**docker-compose -f pocket-core-config-by-volume-mapping.yml up**

**Comment by andrewnguyen22** [comment]
Has this been addressed yet?

**Comment by jeremybeal11** [comment]
This issue was fixed in #358
