### ISSUE TITLE
Crypto functions are using Ethereum

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#386]
**Is your feature request related to a problem? Please describe.**
Currently the staging branch is using Ethereum for all crypto functions. 

**Describe the solution you'd like**
I would like this library to be changed to Tendermint or Cosmos depending on the availability.

**(Optional) Include a BDD test that would satisfy the expected behaviour of the new feature**
BDD for all crypto functions is needed

**Comment by andrewnguyen22** [comment]
This is now a higher priority because I need address generation for testing and it's a blocker

**Comment by luyzdeleon** [comment]
One of the results of this issue must be a first implementation of the `crypto` module interface.
