### ISSUE TITLE
New Logs Interface

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#391]
**Is your feature request related to a problem? Please describe.**
The currently log structure is not sufficient in the organization, flexibility, and readability.

**Describe the solution you'd like**
A new, easy to use log interface that outputs very readable logs in JSON format.

**NOTE**
This interface needs to be accessible throughout the application, similar to the console output.

**Comment by aqt01** [comment]
Closed by
https://github.com/pokt-network/pocket-core/pull/441
