### ISSUE TITLE
At pocket-core startup. Print a status report of all defined env variables and configurations for the pocket-core node client

### ISSUE THREAD

**Issue by aqt01** [pokt-network/pocket-core#398]
**Is your feature request related to a problem? Please describe.**
The current shutdown process is not standardized and the software is not aware of the shutdown signal incoming from docker 

**Describe the solution you'd like**
A standardized way to write the flag definitions similar to the 'man' command format for unix on flag definitions with useful examples

**Comment by andrewnguyen22** [comment]
Closed With #473
