### ISSUE TITLE
Apply best practices and standarization to flag definitions

### ISSUE THREAD

**Issue by aqt01** [pokt-network/pocket-core#399]
**Is your feature request related to a problem? Please describe.**
Flag defintions are not clear and they lack of useful examples

**Describe the solution you'd like**
A new, easy to use log interface that outputs very readable logs in JSON format.

**NOTE**
This interface needs to be accessible throughout the application, similar to the console output.

 with proper definitions and examples

**Comment by andrewnguyen22** [comment]
Closed with #473
