### ISSUE TITLE
Standardize data directory creation

### ISSUE THREAD

**Issue by aqt01** [pokt-network/pocket-core#400]
**Is your feature request related to a problem? Please describe.**
Data directory creation functionality is inconsistent when having environment variables defined and doesn't work when using a new file system path without a directory created

**Describe the solution you'd like**
Data directory should work on file system path where no directory exists and also it should work using the config files of existing directory with consistency and with no conflict with the environment variables

**Comment by andrewnguyen22** [comment]
Moved to https://github.com/pokt-network/pocket-core-deployments
