### ISSUE TITLE
Testing availability of chains.json

### ISSUE THREAD

**Issue by aqt01** [pokt-network/pocket-core#410]
**Is your feature request related to a problem? Please describe.**
Properly test the availability of the chains (blockchain, HostedChains, ChainStruct ..) without affecting the functionality of pocket-core system

**Describe the solution you'd like**
Ping to verify the existence of the Chains available in `chains.json` with proper verification timeout and not crashing in case it doens't find one of them

**Comment by andrewnguyen22** [comment]
closed with #487
