### ISSUE TITLE
Provide a format structure via config flags

### ISSUE THREAD

**Issue by aqt01** [pokt-network/pocket-core#414]
**Is your feature request related to a problem? Please describe.**
We don't give the user the choice of what to log via a field format

**Describe the solution you'd like**
Provide a flag for logging desired fields for the user, it can be similar to 

https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#setting-up-the-access-log

**Comment by andrewnguyen22** [comment]
Closed with #487
