### ISSUE TITLE
Dispatch Functionality

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-core#424]
The dispatch module is going to provide two functions -> SessionInformation and DispatchPeers. The RPC Core needs to know the details of those to generally describe it in the information endpoint. 

The RPC module's job is to provide a clean, secure, RPC that accepts incoming requests to REST like endpoints (<url> -> CRUD operation), routes to the Dispatcher functions, and responds accordingly.

The dispatch related RPC functionality should consist of:

-Session information: 
Is gonna provide them the service nodes and some other metadata for the user.

-DispatchPeers:
Is going to be a quick wrapper from tendermints RPC that cross-checks the network peers and ensures they are operational (alive) nodes.

**Comment by andrewnguyen22** [comment]
Closed with #450
