### ISSUE TITLE
Created standard Pocket Core Query ABCI wrapper

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#429]
**Describe the solution you'd like**
Tendermint's [Query interface](https://tendermint.com/docs/spec/abci/apps.html#query) serves as a free form query interface that needs to be wrapped according to the queries that will be executed by Pocket Core. The objective of this issue is create a standard interface to be used by all queries in order to standardize access to the underlying Query interface.

**Include a BDD test that would satisfy the expected behaviour of the new feature**

**Comment by andrewnguyen22** [comment]
Closed with #450
