### ISSUE TITLE
Define a list of Transactions to be persisted in the Pocket Network

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#431]
**Describe the solution you'd like**
A documented list of all transaction types necessary to the Pocket Network protocol spec. Define parameters and world state requisites for each transaction type.

**(Optional) Include a BDD test that would satisfy the expected behaviour of the new feature**
Include BDD tests describing the validation of each transaction based on parameters and world state.

**Comment by andrewnguyen22** [comment]
Closed with #479
