### ISSUE TITLE
Define a generic Transaction structure

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#432]
**Describe the solution you'd like**
Create a specification of Pocket Network transactions to serve as the basis of each transaction type.

**(Optional) Include a BDD test that would satisfy the expected behaviour of the new feature**
In the case a generic data structure is defined as a result of this issue, there must be BDD tests included to parse and validate that data structure.

**Comment by andrewnguyen22** [comment]
See https://github.com/pokt-network/posmint
