### ISSUE TITLE
Define blockchain namespace for RPC

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#433]
**Describe the solution you'd like**
Pocket Core needs to wrap [Tendermint's RPC](https://tendermint.com/rpc/) interface and expose via the `blockchain` namespace in the Pocket Core RPC interface. The result of this issue must be a document in the `doc` folder that contains a versioned specification of the Pocket Core RPC `blockchain` namespace interface.

**Comment by andrewnguyen22** [comment]
Closed with #487
