### ISSUE TITLE
Create a genesis block specification for Pocket Network

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#435]
**Describe the solution you'd like**
Create a specification as a document in the `doc` folder describing how the genesis block will be passed on to Pocket Network client applications. This specification has to take into consideration:

1. Pre-mine of POKT tokens
2. Pre-allocation of POKT tokens to specific accounts with different amounts
3. Pre-determined stake from block 0 of specific accounts (Application/Node stakes)
4. Any initial state that can be pre-configured at the network launch.

**Comment by andrewnguyen22** [comment]
See https://github.com/pokt-network/posmint
