### ISSUE TITLE
Migrate config.yml from version 2.0 to 2.1

### ISSUE THREAD

**Issue by nelcolon** [pokt-network/pocket-core#464]
**Describe the solution you'd like**
Migrate current config.yml to use version 2.1 and it's syntax.

**Comment by edjroz** [comment]
Consider using CircleCI [practices](https://circleci.com/blog/go-v1.11-modules-and-circleci/) for installing dependencies with `go.mod` and running tests before a build since the assess the functionality rather than compilation.

**Comment by nelcolon** [comment]
After a meeting with Lowell and Luis, we came to the conclusion that config.yml doesn't need to be updated and instead we will be running the image scanning on the repo: pocket-core-deployments
After this issue is complete: https://github.com/pokt-network/pocket-core-deployments/issues/14
