### ISSUE TITLE
Enable Accounts Nicknames 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#507]
When creating a new account, there should be an extra optional command that will bind the newly created address to the nickname. 

For instance:  
`./main accounts create "Alice"`

Then when I show the accounts list I should see:
```
(0) 123ABC
(1) Alice
(2) 456DEF
```

This will allow me to shorthand some commands without typing the address out as well as organize **DApp A** with **wallet A**

**Comment by andrewnguyen22** [comment]
Not going to implement
