### ISSUE TITLE
missing return arguments in CLI-PT2

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#618]
In the CLI, the following flags are missing their helper arguments:

- `./main query node` is missing **nodeAddr** 
- `./main query node-proofs`  **nodeAddr** and optional **height**
- `./main query tx` **???** (this one is missing the the documention https://github.com/pokt-network/pocket-core/blob/staging/doc/cli-interface-spec.md)

**Comment by andrewnguyen22** [comment]
pocket query node -h 
-- reveals `pocket query node <address> <height> [flags]`
pocket query node-proofs -h 
-- reveals `pocket query node-proofs <nodeAddr> <height> [flags]`
Will fix doc/cli spec
