### ISSUE TITLE
Generalize thread safety and mutex

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#65]
Easily generalize the code: `lock.Lock()` and `defer lock.Unlock`

Thoughts:

1. Annotation? @threadsafe
2. Separate function?

**Comment by iajrz** [comment]
locking and unlocking don't always happen in the same places (we won't always need the whole function to behave atomically), so the annotation on its own woulnd't help too much. although another function could work, the gains are marginal.
I think we can drop this issue?
