### ISSUE TITLE
[FEATURE REQUEST] Client implementation in Python

### ISSUE THREAD

**Issue by filips123** [pokt-network/pocket-core#659]
**Is your feature request related to a problem? Please describe.**

There is no way to use Poket Netowork expect with JavaScript, iOS (Swift) and Android. In order to truly become "infrastructure that’s actually decentralized", you should provide a way to use it with other programming languages, one of them should be Python, as one of the most popular and used programming languages.

**Describe the solution you'd like**

You should provide Python (and later other languages as well) client for Pocket Network, and provider for Web3.py.

**Comment by nymd** [comment]
Thank you for the request and we agree!  To further our goal of supporting any blockchain and any infrastructure, more SDKs in various languages are necessary.

As we expand our engineering team we will aim to support other languages and frameworks but we will also be launching a grant program in the near future where we will reward development teams with POKT that contribute SDKs or in other ways to the ecosystem.

Check back in the next quarter to see the grant program in operation and I will update this issue once we have progress on the Python client.

**Comment by nymd** [comment]
If you would use a Python implementation of the Pocket client, please add a thumbs up to the original post. We will be using those metrics to prioritize our client backlog.

**Comment by andrewnguyen22** [comment]
Closed in favor of https://github.com/orgs/pokt-network/projects/106
