### ISSUE TITLE
[FEATURE REQUEST] Client implementation in Flutter / Dart

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-core#684]
To further our goal of supporting any blockchain and any infrastructure, more SDKs in various languages are necessary.

As we expand our engineering team we will aim to support other languages and frameworks but we will also be launching a grant program in the near future where we will reward development teams with POKT that contribute SDKs or in other ways to the ecosystem.

If you would use a Flutter / Dart implementation of the Pocket client, please add a thumbs up to this post. We will be using those metrics to prioritize our client backlog.

**Comment by andrewnguyen22** [comment]
Closed in favor of https://github.com/orgs/pokt-network/projects/106
