### ISSUE TITLE
Change camelCase to snake_case on RPC responses

### ISSUE THREAD

**Issue by oten91** [pokt-network/pocket-core#691]

**Comment by nymd** [comment]
Are there specific responses you're targeting that App Solutions should be aware of as they might change what we're expecting? Thanks

**Comment by andrewnguyen22** [comment]
@oten91 @nymd we need both teams to coordinate this effort if possible. The standard should be set and everyone should be happy

**Comment by andrewnguyen22** [comment]
@oten91 moving forward let's try to put descriptions in issues
