### ISSUE TITLE
Pocket Core CLI version command

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#693]
**Describe the solution you'd like**
Add a `version` command to the CLI. That outputs the current version of Pocket Core, e.g.:

`$  pocket version`
`RC-0.1.0`

**Comment by andrewnguyen22** [comment]
This is tricky because it would just return the version of the CLI and not the App running on tendermint

**Comment by andrewnguyen22** [comment]
Perhaps a better solution is to update the rpc endpoint to provide us with comprehensive version information
@luyzdeleon

**Comment by luyzdeleon** [comment]
I believe still this would be good enough. When dealing with installing binaries, the easier way to confirm that you have the right binary installed is to check the version. In the future if we could display more info on this command then perfect. We could make the output explicity by saying:

```
$ pocket version
CLI Version: RC-0.1.0
```

**Comment by andrewnguyen22** [comment]
Alright, will likely implement both
