### ISSUE TITLE
Wrong URL to Network Identifiers

### ISSUE THREAD

**Issue by joesixpack** [pokt-network/pocket-core#752]
https://docs.pokt.network/docs/service-node-setup-binary#section-staking-your-node

# chains: A comma separated list of chain Network Identifiers(see: https://docs.pokt.network/docs/connecting-your-service-node-to-a-blockchain

...should point to https://docs.pokt.network/docs/supported-networks

**Comment by jeremybeal11** [comment]
@joesixpack done. Thanks for the catch!
