### ISSUE TITLE
CLI ignores --datadir flag

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#782]
**Describe the bug**
Currently the CLI ignores the `--datadir` flag for every command, except `start`.

**To Reproduce**
1.- Create a brand new dir
2.- Run `pocket accounts get-coinbase --datadir <your brand new dir>`
The output will be whatever is in your default datadir folder (`~/.pocket`).

**Expected behavior**
1.- Create a brand new dir
2.- Run `pocket accounts get-coinbase --datadir <your brand new dir>`
3.- The output will be that there is no coinbase account because the keybase is empty.

**Comment by andrewnguyen22** [comment]
FYI: This is only true if core is not running
