### ISSUE TITLE
Unknown db_backend cleveldb, expected either fsdb or goleveldb or memdb exception

### ISSUE THREAD

**Issue by sl-he** [pokt-network/pocket-core#795]
**Describe the bug**
Unknown db_backend cleveldb, expected either fsdb or goleveldb or memdb

**To Reproduce**
1. Just run pocket 0.2.3

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04.3 LTS CLI Mode

**Additional context**
Apr 22 22:40:10: panic: Unknown db_backend cleveldb, expected either fsdb or goleveldb or memdb
Apr 22 22:40:10: #015
Apr 22 22:40:10: goroutine 1 [running]:
Apr 22 22:40:10: github.com/tendermint/tm-db.NewDB(0xfb8281, 0xa, 0xfb6546, 0x8, 0xc000baaf20, 0x17, 0xdf7240, 0x0)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/tendermint/tm-db@v0.2.0/db.go:67 +0x39f
Apr 22 22:40:10: github.com/tendermint/tendermint/node.DefaultDBProvider(0xc0004ae560, 0xc0004ae560, 0x0, 0x0, 0x0)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/node/node.go:66 +0xcb
Apr 22 22:40:10: github.com/tendermint/tendermint/node.initDBs(0xc000032640, 0x11308c0, 0xf9ae40, 0xc0003211e0, 0x40411a, 0x12aa860, 0xeda4c0)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/node/node.go:207 +0x6c
Apr 22 22:40:10: github.com/tendermint/tendermint/node.NewNode(0xc000032640, 0x128c260, 0xc000176a00, 0xc000b88780, 0x1276000, 0xc0004ae4e0, 0xc000bbaa50, 0x11308c0, 0xc000bbaa60, 0x1290f20, ...)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/tendermint/tendermint@v0.32.9/node/node.go:562 +0x50
Apr 22 22:40:10: github.com/pokt-network/pocket-core/app.NewClient(0xc000032640, 0x1290f20, 0xc000124200, 0x0, 0x0, 0x112ff30, 0x1290f20, 0xc000124200, 0x0, 0x0)
Apr 22 22:40:10: #011/home/user/source/pocket-core/app/tendermint.go:39 +0x496
Apr 22 22:40:10: github.com/pokt-network/pocket-core/app.InitTendermint(0x0, 0x0, 0xc000bb6000, 0x2ed, 0xfb2d44, 0x5, 0xfb2d3f, 0x5, 0x1, 0xc000bb6000)
Apr 22 22:40:10: #011/home/user/source/pocket-core/app/config.go:188 +0x485
Apr 22 22:40:10: github.com/pokt-network/pocket-core/app.InitApp(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000bb6000, 0x2ed, 0xfb2d44, 0x5, ...)
Apr 22 22:40:10: #011/home/user/source/pocket-core/app/config.go:92 +0x148
Apr 22 22:40:10: github.com/pokt-network/pocket-core/app/cmd/cli.glob..func36(0x19d2d00, 0x1a0b3f8, 0x0, 0x0)
Apr 22 22:40:10: #011/home/user/source/pocket-core/app/cmd/cli/root.go:73 +0x18d
Apr 22 22:40:10: github.com/spf13/cobra.(*Command).execute(0x19d2d00, 0x1a0b3f8, 0x0, 0x0, 0x19d2d00, 0x1a0b3f8)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
Apr 22 22:40:10: github.com/spf13/cobra.(*Command).ExecuteC(0x19d2a80, 0x4451da, 0x197c740, 0xc000000180)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
Apr 22 22:40:10: github.com/spf13/cobra.(*Command).Execute(...)
Apr 22 22:40:10: #011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
Apr 22 22:40:10: github.com/pokt-network/pocket-core/app/cmd/cli.Execute()
Apr 22 22:40:10: #011/home/user/source/pocket-core/app/cmd/cli/root.go:42 +0x31
Apr 22 22:40:10: main.main()
Apr 22 22:40:10: #011/home/user/source/pocket-core/app/cmd/pocket_core/main.go:8 +0x20

**Comment by luyzdeleon** [comment]
Was missing a requirement for Linux installations: https://docs.pokt.network/docs/setup-pocket-core#section--building-from-source-
