### ISSUE TITLE
pocket query nodes --staking-status staked 0 should query the latest height.

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#797]
**Describe the bug**
Currently running `pocket query nodes --staking-status staked 0` will try to get to get data from the block 0, which is always going to produce empty results.

**Expected behavior**
Use the latest height when the parameter == 0.

**Additional context**
Reported by user Alibaba#0280 on Discord.

**Comment by andrewnguyen22** [comment]
Querying nodes have changed to opts, see spec

**Comment by oten91** [comment]
Was not able to replicate using RC. 0.2.4 (running from docker or OS X).  On RC 0.3.0 functionality  has been updated and seems to work without problems.

Closing it until new a reports arises
