### ISSUE TITLE
App stake CLI not using the correct verification for chains

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#799]
**Describe the bug**
Currently whenever trying to stake an app through the `pocket apps stake` CLI command will output this error, even with the appropiate params:

```
Enter passphrase:
ERROR:
Codespace: pocketcore
Code: 62
Message: "the addr length is not valid"
```

**To Reproduce**
`./pocket_local apps stake <valid address> 1000000 <valid chain id>`

**Expected behavior**
Transaction must be submitted.

**Additional context**
The culprit is this: https://github.com/pokt-network/pocket-core/blob/staging/app/tx.go#L87

Should change `HashVerification` to `ShortHashVerification`.

**Comment by andrewnguyen22** [comment]
Use 4 bytes instead of short hash
