### ISSUE TITLE
invalid chains.json: unexpected end of JSON input

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#821]
**context:**
when I set the validator address for the first time and enter: `pocket start` and cancel out of the prompt: `Enter the ID of the network identifier:` 
I get: ` panic: invalid chains.json: unexpected end of JSON input` when i run `pocket start` again.

**additional info:**
When I viewed the chains.json it was empty, but it was able to run locally when I added the `[ ]` inside the file.

**solution:** 
maybe we can auto-gen the `[ ]` inside of the chains.json file and this will allow someone to just run a pocket node instead of a validator

**Comment by jeremybeal11** [comment]
@andrewnguyen22  and @luyzdeleon this brings up another question, can we enable the CLI to prompt the user whether or not they want to set up a validator or just a pocket node?  If so then it asks for the network ID and etc and not it will just add the `[ ]` in the chains file.

**Comment by andrewnguyen22** [comment]
closed with a6873d779225bf593dbd4cb80d77c4914d52acc7
