### ISSUE TITLE
Prune unstaked validators

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#845]
**Is your feature request related to a problem? Please describe.**
Unstaked validators should not be stored in the AllValidators store

Carefully! Remove unstaked validators from the AllValidators store. Ensure that any work arounds are in place if we are retrieving unstaked validators for any functionality

**Comment by edjroz** [comment]
Ideal point to remove unstaked validators from store 

https://github.com/pokt-network/pocket-core/blob/a238f6438082d684b3858f19a99178b63bf9d9eb/x/nodes/keeper/valStateChanges.go#L66

this is the only point of interaction with unstaked validators neccesary to update the Tendermint
