### ISSUE TITLE
Consolidating terminology around RelayChain

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#868]
**Describe the bug**
Consolidating terminology around non native chain/chains/blockchains/netid/network id/network identifier
(In documentation and code)

**Comment by jeremybeal11** [comment]
terminology should be: 
```
external chains - chains that are outside of pocket
chain id - represents the network running (testnet, mainnet, devnet)
network id - the subnetwork of the external chains(eth rink, BTC mainnet) 
```

**Comment by jeremybeal11** [comment]
Some examples are: 
1. when a user enters in `pocket util generate-chains` it asks them to `Enter the ID of the network identifier:`. When they go to the supported networks [page](https://docs.pokt.network/docs/supported-networks-on-mainnet) to find ETH rinkeby for example, The Network ID shows `4` when in reality it should be `0025` which is under the chainID column. 
2. when a user want to stake their node using `pocket nodes stake <fromAddr> <amount> <chains> <serviceURI> <chainID> <fees>` they go back to the supported networks page and see's that the chainID is `0001` when it shuld be `mainnet` which is under the `network ID` column

**Comment by BenVanGithub** [comment]
I propose that the user facing part of this issue can and should be dealt with now.  The documentation nomencalature is not directly tied to the code nomenclature or vice-versa.
I propose this:
search every page in the docs site., Identify every use of the word "chain"  Determine if it is referring to a relay chain or a pocket blockchain.
Add the appropriate word directly to the existing word.
Therefore:  < chain > would become either < relayChain > or < networkChain >

**Comment by POKT-Discourse** [comment]
This issue has been mentioned on **Pocket Network Forum**. There might be relevant details there:

https://forum.pokt.network/t/ideas-generated-from-the-seedling-quest/631/8
