### ISSUE TITLE
blockReward uses GetValidator.Address instead of using passed address.

### ISSUE THREAD

**Issue by edjroz** [pokt-network/pocket-core#896]
**Is your feature request related to a problem? Please describe.**
`blockReward` receives previous proposer address however it performs a get operation for the validator with the address.

https://github.com/pokt-network/pocket-core/blob/ec9f48d01f324061950e541abf58c2cf8371230a/x/nodes/keeper/reward.go#L44

**Comment by andrewnguyen22** [comment]
Closed with 18ab370aa11c1144ab66b1fa30202d4d8be45528
