### ISSUE TITLE
Manual Peerlist File Feed

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#92]
Use legacy peerlist file and adapt to our needs
Add fields to JSON peer file and unmarshal into struct

**Comment by iajrz** [comment]
Peerlist File currently doesn't contain all the information we need to have for proper operation; for instance, blockhain version information and related.

**Comment by andrewnguyen22** [comment]
Specifically must adapt hosted chain structure to conform to new spec
