### ISSUE TITLE
panic: invalid chains.json: json: cannot unmarshal object into Go value of type []types.HostedBlockchain

### ISSUE THREAD

**Issue by sl-he** [pokt-network/pocket-core#921]
**Describe the bug**
Exception after pocket start with old chains.json (not changed chains.json)

**To Reproduce**
1. Run Pocket core
2. See error

**Expected behavior**
I expected the new version to work with the chains.json file left over from the previous version.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS CLI Mode
 - Version RC-0.3.0

**Additional context**
panic: invalid chains.json: json: cannot unmarshal object into Go value of type []types.HostedBlockchain
#015
goroutine 1 [running]:
github.com/pokt-network/pocket-core/app.NewHostedChains(0xe934a0)
#011/home/user/source/pocket-core/app/config.go:521 +0x770
github.com/pokt-network/pocket-core/app.NewPocketCoreApp(0x12a9a60, 0xc0005963e0, 0x12b9fc0, 0xc000592070, 0xc00014d768, 0x1, 0x1, 0x0)
#011/home/user/source/pocket-core/app/app.go:67 +0xbeb
github.com/pokt-network/pocket-core/app.InitTendermint.func2(0x12a9a60, 0xc0005963e0, 0x12b9fc0, 0xc000592070, 0x0, 0x0, 0xc00014d820)
#011/home/user/source/pocket-core/app/config.go:284 +0x98
github.com/pokt-network/pocket-core/app.NewClient(0x1c0f620, 0x12a9a60, 0xc0005963e0, 0x0, 0x0, 0x1144c00, 0x12a9a60, 0xc0005963e0, 0x0, 0x0)
#011/home/user/source/pocket-core/app/tendermint.go:37 +0x1b7
github.com/pokt-network/pocket-core/app.InitTendermint(0x0)
#011/home/user/source/pocket-core/app/config.go:283 +0x15c
github.com/pokt-network/pocket-core/app.InitApp(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
#011/home/user/source/pocket-core/app/config.go:158 +0xcf
github.com/pokt-network/pocket-core/app/cmd/cli.glob..func49(0x1bb3f20, 0x1c39c60, 0x0, 0x0)
#011/home/user/source/pocket-core/app/cmd/cli/root.go:72 +0xdb
github.com/spf13/cobra.(*Command).execute(0x1bb3f20, 0x1c39c60, 0x0, 0x0, 0x1bb3f20, 0x1c39c60)
#011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1bb3ca0, 0x4473ca, 0x1bc6d20, 0xc000000180)
#011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
#011/home/user/work/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/pokt-network/pocket-core/app/cmd/cli.Execute()
#011/home/user/source/pocket-core/app/cmd/cli/root.go:41 +0x31
main.main()
#011/home/user/source/pocket-core/app/cmd/pocket_core/main.go:8 +0x20

**Comment by luyzdeleon** [comment]
The new structure of the chains.json for RC-0.3.0 is outlined here: https://docs.pokt.network/docs/node-configuration#configuring-your-chains
