### ISSUE TITLE
Arm compatibility

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#943]
**Is your feature request related to a problem? Please describe.**
Currently Pocket Core does not build in Arm architectures.

**Describe the solution you'd like**
For Pocket Core to be buildable in Arm architectures.

**Comment by edjroz** [comment]
@luyzdeleon  Any description or example on why is it not possible to build this for ARM architectures? 

Ideally you should just need to pass in `GOARCH="arm" go build github.com/pokt-network/pocket-core/app/cmd/pocket_core/main.go`. Usually golang would pick the architecture based on the system building.

If the solution you are looking for is to offer multiple builds, the Ideal scenario would be to use a Makefile with proper build commands and flags for different architectures.

**Comment by andrewnguyen22** [comment]
Confirmed build on ARM using:
`GOOS=linux GOARCH=arm`
