### ISSUE TITLE
Pocket Query Ignoring RPC Port

### ISSUE THREAD

**Issue by joesixpack** [pokt-network/pocket-core#994]
**Describe the bug**
Pocket Query appears to be ignoring the RPC port set on the command line when running pocket daemon, the RPC port in config.json and the RPC port on the pocket query command line.

**To Reproduce**
pocket query account --pocketRPCPort 8088 8c7899c15975dd088a00190fdab920ab19e2d098

**Expected behavior**
Should work and return the query.

**Screenshots**
![image](https://user-images.githubusercontent.com/23145642/83641045-d4debf80-a561-11ea-9a8a-01d90fb2eb50.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Comment by luyzdeleon** [comment]
@joesixpack There's a new flag that you can use to use your CLI with a remote node: `--remoteCLIURL`, i.e.

`pocket query account --remoteCLIURL https://myip.com:8081 <your address>`

**Comment by joesixpack** [comment]
Yeah but this isn't really a proper solution.  It should be respecting the DefaultRPC field in the config.json file not going out to the Internet and using https.
