### ISSUE TITLE
Update default config values

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#995]
**Describe the solution you'd like**
Currently the default values of a Pocket Core node configuration do not match the expected values outlined below.

Assumptions: ulimit -Sn has been set to `ulimit -Sn 16384` in the host machine.

1. Open connections 
      GRPCMaxOpenConnections = 2500
     MaxOpenConnections) = 2500
2. P2P
        MaxNumInboundPeers = 250
        MaxNumOutboundPeers = 250
2. AllowDuplicateIP = true
3.  Mempool settings = 
    1. Size = 9000, 
    2. CacheSize = 9000
4. Consensus Params =
             "TimeoutPropose": 60000000000,
            "TimeoutProposeDelta": 10000000000,
            "TimeoutPrevote": 60000000000,
            "TimeoutPrevoteDelta": 10000000000,
            "TimeoutPrecommit": 60000000000,
            "TimeoutPrecommitDelta": 10000000000,
            "TimeoutCommit": 780000000000,
            "SkipTimeoutCommit": false,
            "CreateEmptyBlocks": true,
            "CreateEmptyBlocksInterval": 900000000000,
            "PeerGossipSleepDuration": 100000000,
            "PeerQueryMaj23SleepDuration": 2000000000
5. client_block_sync_allowance = 10
6. max_evidence_cache_entries = 500
7. max_session_cache_entries = 500
8. DBBackend = cleveldb
9. session_db_type = cleveldb
10. evidence_db_type = cleveldb
11. remote_cli_url = http://localhost:8081

**Comment by joesixpack** [comment]
The below is also an expected value if you want /status to be working when pocket query node is not.

            "ListenAddress": "tcp://0.0.0.0:26657",

**Comment by joesixpack** [comment]
Isn't 12 wrong?  Should be https with a domain name matching the certificate.

**Comment by andrewnguyen22** [comment]
@joesixpack The default of 12 should not be an SSL address, instead it should assume pocket core is being run locally (localhost)

**Comment by joesixpack** [comment]
Hmm, why were we told to change it to https and our domain name then?

**Comment by andrewnguyen22** [comment]
@joesixpack this information about changing to https and your domain is accurate, especially for `service url`. Depending on your setup, the CLI may very well need to be your https+domain. However, as a default, localhost is the standard
