### ISSUE TITLE
Add --mainnet and --testnet flags

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#996]
**Describe the solution you'd like**
After the mainnet launch, we will be having fixed genesis and default configs for each network. Create 2 flags `--mainnet` and `--testnet` that reflect these configs, such that the user can easily start a node and connect to it. 

The expected behaviour is as follows:

`pocket start --testnet` should start a node using the testnet genesis and testnet default Seed Nodes list.
`pocket start --mainnet` should start a node using the mainnet genesis and mainnet default Seed Nodes list.
`pocket start` with no flag should default to mainnet.

**Comment by andrewnguyen22** [comment]
@luyzdeleon I believe I need the genesis files to execute this issue

**Comment by luyzdeleon** [comment]
Updated the issue to reflect that not only the genesis file will vary, but also the Seed Node list.
