### ISSUE TITLE
CLI transactions confirmation prompt

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#998]
**Is your feature request related to a problem? Please describe.**
Currently a user of the CLI could be bound to make mistakes when inputting fields into the CLI for transactions.

**Describe the solution you'd like**
When the user runs the command, a prompt showing a summary of his inputs and a `[Y/N]` input should appear, letting the user review his transaction before sending it into the network.

**Comment by andrewnguyen22** [comment]
This UX/UI nicety seems like it should be left to the higher level products, no? @luyzdeleon

**Comment by andrewnguyen22** [comment]
Closing for lack of response, activity, and interest. For now passphrase is enough confirmation at this time
