### ISSUE TITLE
CLI output improvements

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#999]
**Is your feature request related to a problem? Please describe.**
Currently CLI output is not easy to read, nor are errors explanations useful.

**Describe the solution you'd like**
Whenever outputting structs or json-like strings to the CLI, they should be "pretty pinted" and errors should not have stack traces, rather a nice explanation of the error, either it being missing fields or steps on how to correct it would be better.

**Comment by andrewnguyen22** [comment]
This issue is very broad, I would like more actionables here before anything is completed @luyzdeleon
